### ISSUE TITLE
Installation en boucle de paquet manquant

### ISSUE THREAD

**Issue by ghost** [TuxML/ProjetIrma#1]
J'ai lancé tuxml, il installe en boucle le package 'openssl.h' et 'bio.h'

**Comment by micleb** [comment]
Tu peux réessayer ?
Je viens de commit une nouvelle version

**Comment by micleb** [comment]
Le problème est réglé, je parsais mal le fichier de logs ;-)

**Comment by Heartbroken-Git** [comment]
Petit follow-up du problème. D'après @micleb c'est probablement réglé. Mais il faudrait réaliser des tests pour s'assurer que ça soit le cas.

**Comment by Heartbroken-Git** [comment]
Alors, normalement c'est bon. Sauf que c'est très difficile à tester. Comme depuis la réouverture on a plus rencontré le problème on ferme l'issue. On la rouvrira si jamais le problème réapparaît.
