### ISSUE TITLE
Is randconfig random? 

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#10]
Bonjour, 

j’ai pensé à une petite expérience pour “valider” à la fois le travail côté randconfig et le travail en cours sur la construction d’un CSV à partir de multiples .config...
L’idée est la suivante:
 * lancer N fois randconfig _sans compiler_: l’objectif est d’obtenir N .fichiers .config
 * produire un CSV à partir des N fichiers .config (logiquement on devrait obtenir N+1 lignes)

Cette expérience est tout d’abord un bon cas de test (pour la transformation vers CSV). Ce sera aussi l’occasion de déterminer le nombre d’options, qu’elles soient actives (y), non actives (n), ou module (m) (normalement cela devrait correspondre au nombre de colonnes dans le CSV). 
Enfin, de manière plus exploratoire, et à l’aide du CSV, on peut très certainement vérifier le côté “random” de randconfig (ie est-ce que randconfig est vraiment random?). Evidemment au plus N est élevé (10^6?), au plus ce sera intéressant d'un point de vue statistique. 

En parcourant le code ici:
https://github.com/TuxML/ProjetIrma/blob/master/csvgen/csvGenerator.py

je me rends compte:
 * modulo un refactoring pour isoler la partie qui transforme ".config => CSV", il suffit d'une petite boucle qui appelle randconfig (par appel système) N fois 
 * les noms des options doivent être dans le "header" du CSV, et chaque ligne doit être une "configuration" (en gros, il faut "renverser" le CSV tel qu'il est généré actuellement)

**Comment by Heartbroken-Git** [comment]
J'ai assigné @Aexelion pour la partie randconfig et @PLeLuron, l'auteur du générateur vers CSV. Par contre j'ai pas encore mis de labels sur l'issue, à voir avec les intéressés.

**Comment by Aexelion** [comment]
Alors d'après ce que j'avais vu, le randconfig est bien random, je ferme l'issue pour le moment et si on trouve des infos contradictoires je la ré-ouvrirais.
