### ISSUE TITLE
HOWTOS

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#100]
Hi, 

it would be nice to have some "howto" (aka tutorials/documentation with step-by-step instructions). 
The idea is to write a proper document for new users or new developers. 

A couple of questions below (I've tried to summarize the user story or the basic motivation) 

# How to use TUXML (in one command line)? 

I am a possible "contributor", a student, a friend, I like the projet and I am willing to loan my machine to gather some compilation data. How can I help? 

Ideally one command line that launches the Docker and TUXML ;) 
But maybe that's trickier and Python3 + some downloads are needed 

# How to update the Docker image? 

Let's say I want to install a new package (because we've identified it's needed for compiling many configurations). How to update the image? 

# How to update the IGRIDA Debian image? 

Same as previous question. 

# How to pre-set some options (specialization)? 

I want to necessarily activate or deactivate some options (and then it's random). 
How to do that with Docker or IGRIDA? 

Can we temporarily specialize the compilation process? 

# How to compute make tinyconfig?

(with Docker or IGRIDA) 

# How to (re-)compile a specific configuration?  

I have a .config on my machine. I want to compile it. 

# Where is the code to instrument/investigate incremental compilation? 

# Let's say we want to launch a new campaign on another version of the Linux kernel. What's the impact on the overall code?

**Comment by alemasle** [comment]
The README.md has been updated and a wiki has been written.

**Comment by FAMILIAR-project** [comment]
Some questions/remarks:

`./MLfood.py 100 --dev`
--dev will sent the data to which database? 

master_spring.py relies on spring_core.txt (it should be documented?) and the problem I had is that the output/error folder points out to alemasle (all jobs fail for this reason). 
As a fix I have edited sprint_core.txt
I propose to document it and/or further parameterize master_spring 

For the HOWTO "Where is the code to instrument/investigate incremental compilation?"
Can you also comment on scripts you've developed to analyse the incremental compilation results? 

For the HOWTO "Let's say we want to launch a new campaign on another version of the Linux kernel." 
can you elaborate more? 

The impacts are on  the Python scripts, the database (?), the Docker image, etc. but where exactly? 

Last request: can you document a bit the database schema, especially what all "sizes" means and are collected?

**Comment by alemasle** [comment]
Every way of compilation we have brings to the same database "prod".
I am going to document more.

**Comment by alemasle** [comment]
I will add a new page to the wiki about the database
