### ISSUE TITLE
bdd2csv: inside the VM?

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#101]
bdd2csv extracts a CSV out of the database. 
In my experience, the process can be quite long (and can require lot of memory). 

I suspect it is long because of the connection with the database hosted by the ISTIC virtual machine. 
A possible workaround would be:
 * to execute bdd2csv inside the VM (the exchanges with the database would be "local" in this cas)
 * to offer a way to download the resulting CSV 

Two unclear points that need some tries/experiments:
 * the VM should have a lot of memory to build the CSV 
 * does the solution really reduce the time? (I assume that the cost of downloading the CSV is less than the cost of exchanging with the database)

**Comment by alemasle** [comment]
When i was writing bdd2csv i made tests, the things that take all the time are files. When you make the SQL request for config, output, std or err log it will take longer than whitout. Otherwise the ISTIC connection is pretty fast ( ~90 Mb if i remember well), almost the same than the IRISA
