### ISSUE TITLE
Many files located at the "root" of the project

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#105]
Hi, 

I think we can do some "refactoring" and moving some files in some folders. 
Two benefits:
 * less noise when browsing the project 
 * more structure

Let's take an example: bloat-o-meter. 
I guess we can create a folder "incremental_compilation" and put this file there. 

We need to modify the Python code perhaps.

**Comment by alemasle** [comment]
Architecture refactored
