### ISSUE TITLE
"Core" git project

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#106]
Hi, 

I just realized we have a "Core" github project for updating the image. 
It's quite strange since we have to maintain the consistency between "Core" and "ProjetIrma". 

For example editing tuxml.config in ProjetIrma is not sufficient to propagate the changes in the Debian/Docker images. 
We should do better here

A consequence of this problem is that for instance the Debian image has not been updated for the last experiments (10 days?) with the very last tuxml.config, omitting two options that have been pre-set
```
CONFIG_LOCK_STAT=n
CONFIG_X86_VSMP=n
```

note: I've not right access to Core project

**Comment by Heartbroken-Git** [comment]
I'm currently in the process of making your account `maintainer` of the organization's project.
However since I'm not maintainer of *Core* @CaptainMexiko will have to take a look and give you the rights.
I'm available here on GitHub and sometimes on Slack should you need more from me.

**Comment by ghost** [comment]
It's not me that create _Core_, @alemasle did it.

**Comment by Heartbroken-Git** [comment]
@FAMILIAR-project, you should now have full administrative access to the TuxML organization and should thus be able to both read and write on every repo and create/archive/remove repositories.
I've also invited @acherm to the org in the newly created supervision team.
You are obviously free to edit the team layouts I've started to put together to manage a bit better the org's users.

**Comment by FAMILIAR-project** [comment]
Thanks a lot!

As far as I understand, *Core* repository aims to produce an image for IGRIDA http://igrida.gforge.inria.fr/ without actually relying on Docker (it is a custom Debian image https://github.com/TuxML/ProjetIrma/wiki/How-To-(Main-questions)#how-to-update-the-igrida-debian-image). I must admit the description of *Core* is misleading and lead to some confusion ("The content in the Docker image from TuxML/ProjetIrma")

@alemasle can you confirm it? 

The *Core* repository is un-synchronized to the dev (ProjetIrma). It is a quite of "clone and own" (or copy and paste) which has one consequence: each time we're modifying dev branch of ProjetIrma, Core cannot benefit from it (we have to do a manual step to propagate the modifications). 
For instance, if we change the "hardware details extraction" procedure or the tuxml.config (for specialization) in the dev branch, we have to think about updating Core. 

@alemasle did you have a specific procedure/process for updating Core? 

I am sure we can have a script migration to automate this task.

**Comment by alemasle** [comment]
Yes, all has been described in the wiki, section "How to". Core is an independant repo used only for the custom Debian image for igrida.
