### ISSUE TITLE
MLfood does not pull the Docker image

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#109]
Hi,

It seems that the Docker image tuxml/tuxmldebian:dev is not updated by MLfood. 
Subprocess calling docker pull is not called when using in non-silent mode (the default one). 
It's strange, right?
https://github.com/TuxML/ProjetIrma/blob/dev/MLfood.py#L182-L190

I'll uncomment some lines of code. 
In general, I am not sure we really need sudo privileges.

**Comment by Luisky** [comment]
Hi,
It's my fault, I commented line 186 locally and forgot to not commit MLfood.py in the process. I'm going to revert that, Thank you.

as for sudo, from what I could gather if the user launching MLfood is in the docker group it isn't necessary.
