### ISSUE TITLE
Checking the boot of a kernel

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#111]
Hi, 

We need to find an automated procedure that assess whether a compiled Linux kernel can boot or not.
Currently, everything is implemented there:
https://github.com/TuxML/ProjetIrma/blob/dev/core/tuxml_bootCheck.py 

but the procedure does not work well and consumes some times. 
It's a bit related to this issue:
https://github.com/TuxML/ProjetIrma/issues/43

We need to find another procedure or improve the current one.

**Comment by FAMILIAR-project** [comment]
I suggest the following tasks, each can be considered/explored by one person:

 * try to compile a Linux kernel (not with TUXML, on your local disk) and manually boot it with QEMU following tutorials like: http://ncmiller.github.io/2016/05/14/linux-and-qemu.html https://www.collabora.com/news-and-blog/blog/2017/01/16/setting-up-qemu-kvm-for-kernel-development/

 * try to reuse Intel 0day infrastructure: https://github.com/intel/lkp-tests which includes some procedures to check the boot of a kernel (see https://github.com/intel/lkp-tests/blob/master/rootfs/kexec/run-in-kvm.sh) 

 * try other tools documented here: https://elinux.org/images/9/9f/Linux-Kernel-Testing-Where-are-we.pdf including https://kernelci.org/ https://kerneltests.org/

**Comment by JulienRC** [comment]
I tried the first tutorial (http://ncmiller.github.io/2016/05/14/linux-and-qemu.html) at home on Ubuntu 16.04 LTS and I have a problem to install packet
In the tutorial it's the first line "dnf install ncurses-devel kernel-devel kernel-headers openssl-devel"
I am on Ubuntu so I wrote sudo apt-get install ..." (dnf is for Fedora)
I have "Impossible to find the packet ncurses-devl, kernel-devel, kernel-headers, openssl-devel"
Does anyone try this and get something different ?

**Comment by Heartbroken-Git** [comment]
FYI, while I do not know for the other packages, note there are no `ncurses-devel` package on the debian repos, it is named `ncurses-dev` instead if I'm not mistaken.
That should solve your issue, and the problem is probably the same for the other packages :wink:

**Comment by valentinpetit** [comment]
We succesfully booted, on 2 differents VM ( debian 9 and Ubuntu 18)
But, trying to adapt the first tutorial to our project, we detected an issue about the PATH argument.
it's initialized as an empty string in tuxml_settings.py (line 24-25)
`## Path to the linux sources
PATH = ""`

But we don't see anywhere else in the project where the value is modified.
We might need it, in tuxml_bootCheck.py (line 55-56) 
`procId = subprocess.run([cmd, "-kernel", tset.PATH + "/arch/x86_64/boot/bzImage", "-initrd", tset.PATH + "/arch/x86_64/boot/initrd.img-4.13.3",
                           "-m", "1G", "-append", "console=ttyS0,38400", "-serial", "file:serial.out"], stdout=subprocess.DEVNULL, stderr=tset.OUTPUT)
`
