### ISSUE TITLE
Specialization fails

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#112]
Recent compilations (~cid > 119000) are supposed to use the following predefined values:
```
CONFIG_64BIT=y
CONFIG_DEBUG_INFO=n
CONFIG_DEBUG_INFO_SPLIT=n
CONFIG_UBSAN_SANITIZE_ALL=n
CONFIG_GCOV_PROFILE_ALL=n
CONFIG_DEBUG_INFO_REDUCED=n
CONFIG_RANDOMIZE_BASE=n
CONFIG_X86_NEED_RELOCS=n
CONFIG_KASAN_OUTLINE=n
CONFIG_UBSAN_ALIGNMENT=n
CONFIG_USB_SERIAL_OPTICON=n
CONFIG_KASAN=n
CONFIG_KCOV_INSTRUMENT_ALL=n
CONFIG_XFS_DEBUG=n
CONFIG_MAXSMP=n
CONFIG_FW_LOADER_USER_HELPER=n
CONFIG_STRICT_MODULE_RWX=n
CONFIG_DEBUG_INFO_DWARF4=n
CONFIG_AIC7XXX_BUILD_FIRMWARE=n
CONFIG_AIC79XX_BUILD_FIRMWARE=n
CONFIG_WANXL_BUILD_FIRMWARE=n
CONFIG_LOCK_STAT=n
CONFIG_X86_VSMP=n
CONFIG_CC_OPTIMIZE_FOR_SIZE=y
CONFIG_OPTIMIZE_INLINING=y
CONFIG_SLOB=y 
```

I've implemented a Python script for verifying that, indeed, such values are in the .config file of recent entries.

It seems that sometimes there are some unexpected values:
 * CONFIG_SLOB is **not** necessarily active ("y")
 * CONFIG_FW_LOADER_USER_HELPER is **not** necessarily inactive ("n")
 * CONFIG_STRICT_MODULE_RWX is **not** necessarily inactive ("n")

note: experiments have been made with IGRIDA and its tuxml.config (see "Core" repository) 

Several hypotheses can be made:
 * there is actually an option/constraint that unexpectedly forces CONFIG_SLOB to "no" (or CONFIG_FW_LOADER_USER_HELPER to "yes" and  CONFIG_STRICT_MODULE_RWX to "yes")
 * IGRIDA version of TUXML has a bug 
 * randconfig is terrible and overrides preset values

**Comment by malocharo** [comment]
After a bit of test it seems like there is a constraint that force the value of some options. For example CONFIG_SLOB depend from CONFIG_EXPERT. 
It means that everytime I find CONFIG_SLOB=n, CONFIG_EXPERT=n too, and vice-versa.

`make  randconfig`  override some options we preset if they lead to a non-working config that will fail at COMPILATION. It might not boot&run but it should compile everytime.

https://patchwork.kernel.org/patch/8974681/ 
https://www.kernel.org/doc/Documentation/kbuild/kconfig.txt

I will do others tests but this seems to be the reason of thoses bug

**Comment by FAMILIAR-project** [comment]
OK, I propose to write an external Python script that launches `make randconfig` N times (eg N=1000) and that quantifies how many configurations are not coherent with our pre-settings. 
note: we can use this script with different orders of preset options to see the effect (if any). 

This work can serve several purposes:
 * show the weaknesses of make randconfig 
 * develop a brute force procedure that will call make randconfig as many times as needed until having relevant configurations (relevant means here: configurations contain all preset values) 
 * we can also explore why randconfig is wrong. 
 * finally we can explore the alternate use of Kconfiglib https://github.com/ulfalizer/Kconfiglib 

reminder: something like
`KCONFIG_ALLCONFIG=... make randconfig`
for calling make randconfig with preset values

**Comment by FAMILIAR-project** [comment]
@malocharo can you commit/report on your progress here? Thanks!

**Comment by FAMILIAR-project** [comment]
We have now a correct procedure...

`python3 special-config/kconfig_checker.py`

with nrep=100

```
pre-set options to check ['CONFIG_64BIT=y', 'CONFIG_DEBUG_INFO=n', 'CONFIG_DEBUG_INFO_SPLIT=n', 'CONFIG_UBSAN_SANITIZE_ALL=n', 'CONFIG_GCOV_PROFILE_ALL=n', 'CONFIG_DEBUG_INFO_REDUCED=n', 'CONFIG_RANDOMIZE_BASE=n', 'CONFIG_X86_NEED_RELOCS=n', 'CONFIG_KASAN_OUTLINE=n', 'CONFIG_UBSAN_ALIGNMENT=n', 'CONFIG_USB_SERIAL_OPTICON=n', 'CONFIG_KASAN=n', 'CONFIG_KCOV_INSTRUMENT_ALL=n', 'CONFIG_XFS_DEBUG=n', 'CONFIG_MAXSMP=n', 'CONFIG_FW_LOADER_USER_HELPER=n', 'CONFIG_STRICT_MODULE_RWX=n', 'CONFIG_DEBUG_INFO_DWARF4=n', 'CONFIG_AIC7XXX_BUILD_FIRMWARE=n', 'CONFIG_AIC79XX_BUILD_FIRMWARE=n', 'CONFIG_WANXL_BUILD_FIRMWARE=n', 'CONFIG_LOCK_STAT=n', 'CONFIG_X86_VSMP=n', 'CONFIG_CC_OPTIMIZE_FOR_SIZE=y', 'CONFIG_OPTIMIZE_INLINING=y', 'CONFIG_SLOB=y']
[[], ['CONFIG_SLOB=y']]
0.29
```

basically 1 out of 3 configurations do not contain CONFIG_SLOB=y (despite our pre-settings)

So now two questions:
 * Is it a bug of randconfig? Why the behavior is like this? 
 * Can we find a workaround by changing the order of pre-set options?

**Comment by malocharo** [comment]
So CONFIG_SLOB depends on CONFIG_EXPERT. 
After adding it to tuxml.config everything works fine.
I tried to change the position of CONFIG_EXPERT, but it doesn't matter if it comes before or after CONFIG_SLOB, it always works.

I assume that sometimes CONFIG_EXPERT wasn't set to 'y' even if CONFIG_SLOB depend on it, that's why CONFIG_SLOB was not set as well.. 
So it might be a bug of randconfig that is unable to find the dependances of a pre-set options. But I'm not sure about that.

**Comment by acherm** [comment]
@malocharo wouah brilliant! you're right, thanks a lot! 

I've commited a new version which includes the ability to add CONFIG_EXPERT=y and test with it
d94cac5 

Maybe we should put an issue on the LKM (mailing list) about randconfig... A "minimal" example showing the problem is worth needed. We can work on it if you want

**Comment by FAMILIAR-project** [comment]
I'm closing the issue and create a new specific one https://github.com/TuxML/ProjetIrma/issues/126
