### ISSUE TITLE
problems and correction in qemu tutorial

### ISSUE THREAD

**Issue by ernael** [TuxML/ProjetIrma#114]
http://ncmiller.github.io/2016/05/14/linux-and-qemu.html
to do before busybox configuration
	mv -f busybox-1.24.2/ kdev/
	copy linux kernel
	cp -rf /TuxML/linux-4.13.3/ ~/kdev/linux

Boot with Qemu
delete ligne "-enable-kvm"

problem exiting qemu
 ctrl-A X dosent work
 exit cause kernel panic

**Comment by FAMILIAR-project** [comment]
Now the plan is:
 1. to automate the execution of the tutorial with a script in Bash (says). There might be a phase in the script that requires user intervention but we should be able to automate as much as possible. It is also necessary to redirect the output messages into a file (log file) such that we can parse messages typically to "grep" the "Boot took XXX seconds" (we can kill qemu process once finished)
 2. to parameterize the script in such a way we can check the bootability of _any configuration_ (not only x86_64_defconfig) 
 3. to identify which parts of the script can be done "once and for all" inside the Docker image 
 4. to integrate the solution into TUXML

Steps 3 and 4 should be done in connection with the team in charge of Docker. 
Steps 1 and 2 are the most urgent and difficult

**Comment by JulienRC** [comment]
TODO :

Ecrire une documentation pour les utilisateurs s'ils veulent éxécuter le scriptBootKernel.sh
Renvoyer la sortie dans un fichier log jusqu'à vérifier le temps de boot "boot in x seconds" or "kernel panic"
Dans tous les cas il faut tuer le processus

**Comment by JulienRC** [comment]
Forcer le Y dans le script
Rediriger la sortie dans un fichier log, faire un grep pour récupérer le temps de boot et tuer le processus juste après 
Implanter la première partie du script en dur dans le container pour ne pas avoir à le refaire à chaque fois 
Trouver une solution pour ne pas avoir à configurer busybox interactivement

**Comment by ernael** [comment]
remove - make kvmconfig
resolve - can exit Qemu with Ctrl-A X
exit cause kernel panic because it's interpreted by the kernel not Qemu
