### ISSUE TITLE
kernel_generator workflow

### ISSUE THREAD

**Issue by mipicard** [TuxML/ProjetIrma#115]
Following : #108

Here goes the testing and implementing workflow of kernel_generator.py

Functionality :

- [x] update and download image 
- [x] run basic compilation
- [x] incremental compilation (test other thing before)
- [x] saving log
- [x] silent mode
- [x] specific config file
- [x] tiny version
- [x] Supporting different linux4 version
- [x] Unit testing for the majority of the content of the image

Testing :

- [x] Update when needed
- [x] Run from scratch
- [x] Use local version
- [x] Multiple run
- [x] Tiny and Specific config file
- [x] Silent mode

**Comment by FAMILIAR-project** [comment]
Great! 
I think we also need to write a documentation for how to use it

**Comment by FAMILIAR-project** [comment]
The "tiny" option is actually useful and should be implemented. 
It should be noted that we need to call tiny with something like:
KCONFIG_ALLCONFIG=x64bit.config make tiny

with the file content of x64bit.config being: 
CONFIG_64BIT=y
since we want to compiler 64 bits architecture.

**Comment by mipicard** [comment]
About the new support of 4.X version for linux :
How about building a locally new docker image for the linux version that we could delete after (or keeping it for ensuring that local argument will not try to download the kernel)?
It will accelerated each run if we run a lot of container, because we will not have to re-download every time the kernel.

**Comment by FAMILIAR-project** [comment]
@mipicard good idea, we could pre-package Docker images for specific versions... but let's do it simple first ;)

**Comment by mipicard** [comment]
Only things needed right now is to document it inside the wiki.
So i will close this issue.
