### ISSUE TITLE
docker_image_tuxml workflow

### ISSUE THREAD

**Issue by mipicard** [TuxML/ProjetIrma#116]
Following : #108 

Here goes the testing and implementing workflow of docker_image_tuxml.py

Functionality :

- [x] Build image
- [x] Push image
- [x] Add more dependencies to image
- [x] Rebuild from scratch
- [x] Retrieve TuxML file (done, but will need refactoring)
- [x] Cleanup after build
- [ ] Other?

Testing :

- [x] Build (and rebuild)
- [x] Push
- [x] Tagging
- [x] Adding dependencies
- [ ] Other?

- [ ] Documentation of the goal, functionality and workflow of this script

**Comment by FAMILIAR-project** [comment]
Great! 
I think we also need to write a documentation for how to use it

**Comment by FAMILIAR-project** [comment]
Great job! We definitely need a documentation (user doc, HOWTO)

**Comment by mipicard** [comment]
The documentation is in progress along the project report for the university. So, i will close this issue.
