### ISSUE TITLE
Docker and user right

### ISSUE THREAD

**Issue by mipicard** [TuxML/ProjetIrma#118]
Since the beginning of this project, we use get-docker.sh to install docker and run every docker command with sudo.
But that's not a good practice.

I propose that we add a new layer to get-docker.sh to ensure that the installation of docker goes right and that the user will have the right to use docker without sudo.

The workflow for this is pretty simple :
- Install docker (or check that it's already installed before hand)
- create the docker user group
- add the current user to the docker group
- reload user right without logging in and out.

**Comment by psaffray** [comment]
https://docs.docker.com/install/linux/docker-ce/debian/

**Comment by psaffray** [comment]
WARNING : 
The docker daemon always run as the root user.
A malicious user could start a container where the /host directory is the / directory on your host; and the container can alter your host filesystem without any restriction.
Given that, we should ask the user if he wants to be added to the docker group or not.
If the user is informed, then it would be his responsibility.
@mipicard

**Comment by psaffray** [comment]
```
#!/bin/bash

### FOR DEBIAN USERS ###

# but : rendre la version docker installée stable;
# ajout du repo docker
# install a partir du repo
# un apt-update mettra docker à jour
# ajoute l utilisateur au groupe docker s'il le désire.


sudo apt-get update
# Install packages to allow apt to use a repository over HTTPS
sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg2 \
    software-properties-common

curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -

sudo add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"

sudo apt-get update
sudo apt-get install docker-ce # docker-ce-cli containerd.io

read -p "Voulez-vous ajouter l'utilisateur courant au groupe docker?(y/n)" CONFIRM

if [[ $CONFIRM =~ [yY](es)* ]]
then
  sudo usermod -aG docker $USER
  exec su -l $USER
fi
```

**Comment by psaffray** [comment]
[About Docker and user rights.txt](https://github.com/TuxML/ProjetIrma/files/3098262/About.Docker.and.user.rights.txt)

le fichier de doc que j'avais écrit qui explique pourquoi on choisit d'ajouter l'utilisateur au groupe  docker et ce que ça implique, sans doute à intégrer dans le "getting started" du wiki
