### ISSUE TITLE
Comments of a new user of TuxML  

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#14]
Hi, 

J'ai essayé d'utiliser TuxML.
Quelques commentaires au fil de l'eau:
 * pour lancer tuxml.py, `#!/usr/bin/python3` ne fonctionne pas parfois (sous MacOS c'est /usr/local/bin/python3) donc il faut le lancer ainsi python3 core/tuxml.py
 * en pré-requis il faut télécharger l'archive du kernel (le préciser dans le README.md?) wget https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.13.3.tar.xz
 visiblement il vaut mieux le positionner dans un dossier TuxML `os.system('/TuxML/core/tuxml.py /TuxML/linux-4.13.3 --debug')`
 * [-] Please run TuxML as root, use --help to print help: Pourquoi? est-ce vraiment nécessaire? dangereux et pas du tout rassurant! 
 * sous MacOS: cela s'arrête ici 
[-] Unsupported package manager
ce qui n'est pas illogique ;) même s'il y a un package manager comme brew... mais clairement on ne va pas s'amuser à supporter MacOS.

La suite plus tard, avec une machine Linux pour essayer tuxml ;) 

ce qui n'est pas encore clair sur la doc. c'est quelle commande lancer au final: tuxLogs? MLfood? tuxml.py? 

btw pourquoi MLFood est à la racine et pas dans "core"?

**Comment by alemasle** [comment]
Le README a été mis a jour afin de mieux comprendre l'utilisation de la commande principale MLfood.py et l'utilsation générale du projet à ce stade la.
Le support MacOS n'est pas prévu non plus et le seul fichier a télécharger est MLfood.py pour une utilisation simple de compilation multiple sans modification prévue des fichiers.
