### ISSUE TITLE
Documentation of an advanced use case: compilation inside Docker tuxml 

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#140]
Hi, 

It's neither a bug, nor a feature... 
But it would be nice to write a small tutorial about the following use case. 

Basically, a user wants to compile a specific configuration but before she needs to install some tools/packages that are perhaps not in the Docker image.
A concrete example: we have some configurations for which we know they fail at build/compilation time; we want to explore whether the installation of some tools avoid the build failure. 

Originally I was thinking something like:
 * step 1: install/download the docker image (perhaps with `python3 kernel_generator.py --tiny`)
 * step 2: copy the .config (external to the Docker image) into the Docker image and into the source directory of Linux 
 * step 3: enter inside the Docker (TODO: what's the command?)
 * step 4: do your stuff (eg install tools)
 * step 5: enter in the source directory of Linux and type `make` (if I'm not wrong it's sufficient since it will see a .config and compile it)
 * end 

note1: it's quite an ad-hoc process and it should remain so (no need to over-engineer TUXML for handling this case)... just we need the concrete commands ;)  
note2: we can include it into the Wiki, and so in your report... 
note3: maybe it's related to our tries with the boot (we follow a similar process: entering inside Docker, doing ad-hoc stuff, and "testing")

**Comment by Luisky** [comment]
Hi, I've added a small tutorial for this use case here -> https://github.com/TuxML/ProjetIrma/wiki/User_documentation

Some feedback on this would be greatly appreciated !

**Comment by mipicard** [comment]
I will add some correction or precision, but overall, it's very good. Good job 👍

**Comment by Luisky** [comment]
Thanks, about that I forgot to precise something about running the container with "docker run -it" and then leave it without stopping it, Ctrl+P then Ctrl+Q should do the trick, it's all in there: https://stackoverflow.com/questions/25267372/correct-way-to-detach-from-a-container-without-stopping-it

**Comment by psaffray** [comment]
Great, I was on it but it is not a problem. Here are some changings that I can see : 
docker repo adress :
tuxml/tuxml:prod -> tuxml/tuxmldebian:prod
Also, I don't know the exact path of the .config file, but I guess it would be
docker cp .config your_container:/TuxML/linux-4.13.3/.config"
I don't see anything else yet.
Thank you!
nb : I may also add the following command at the beginning since docker's daemon does not start automatically on my machine:
sudo service docker start

**Comment by FAMILIAR-project** [comment]
It sounds great thank you! 
I will "test" your tutorial in a few minutes ;)

**Comment by Luisky** [comment]
Thx for the feedback @psaffray, 
About the repo, on my computer it's tuxml/tuxml:prod so I say we keep both tuxml/tuxml:prod & tuxml/tuxmldebian:prod.

And you're definitely right about the linux sources path I'll fix that right away !

**Comment by mipicard** [comment]
tuxmldebian is the old image, now the only usable image is tuxml

**Comment by JulienRC** [comment]
I thought to update the docker image, we must execute python3 docker_image_tuxml.py ?
I also change the design

**Comment by mipicard** [comment]
We have 2 way to update the image :
 - use kernel_generator.py
 - use docker_image_tuxml.py --update

**Comment by FAMILIAR-project** [comment]
It's working, great! 
Thanks
