### ISSUE TITLE
What are the relevant data of the error logs?

### ISSUE THREAD

**Issue by jualvespereira** [TuxML/ProjetIrma#144]
Some relevant information that should be considered for clustering:

'make.*: \*\*\*.+'
'.* 1:.+'
'.* error:.+'
'.* undefined reference.+'

**Comment by FAMILIAR-project** [comment]
can you move this issue to https://github.com/TuxML/compilation-analysis/issues (ie create the same new issue https://github.com/TuxML/compilation-analysis/issues)?
