### ISSUE TITLE
An imposed configuration as input to TuxML

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#15]
Hello, 

Ce serait pas mal de permettre d'imposer une configuration spécifique à TuxML (plutôt que de passer par randconfig). 
Ce serait un paramètre de la commande. 

Use cases: 
 * je voudrais qu'on puisse donner à TuxML une configuration comme allyes ou allno ou alors une configuration "custom" 
 * reproduire une compilation sur une config donnée  

PS: le "use case" principal est toujours d'utiliser randconfig, c'est juste un "use case" additionnel et intéressant IMHO

**Comment by micleb** [comment]
Pour reproduire une config donnée il faut utiliser l'option `-d` ou `--debug` de tuxml avec le KCONFIG_SEED

Par exemple : `./tuxml.py path/to/linux/sources/ -d 0xdeadbeef`

Ce que je pourrais faire c'est "étendre" cet argument (--debug) pour qu'il supporte aussi un chemin vers un .config custom.

Pour allyes ou allno ça ne devrait pas poser trop de problèmes, je verrai ça avec @Aexelion.

**Comment by FAMILIAR-project** [comment]
> Ce que je pourrais faire c'est "étendre" cet argument (--debug) pour qu'il supporte aussi un chemin vers un .config custom.

Oui! Je préfère cette solution: plus simple et générale que le seed

**Comment by micleb** [comment]
Ca y est, on peut désormais spécifier un fichier particulier à tuxml.py

Ces deux commandes pourront être exécutées :
`./tuxml.py /path/to/sources -d 0xdeadbeef`
`./tuxml.py /path/to/sources -d /path/to/your/custom/.config`

**Comment by micleb** [comment]
Concernant les configs allyes et allno, en soit ce sont déjà des configs "custom".
Donc je trouve que c'est un peu overkill de rajouter 2 options à tuxml qui, même utiles, seront rarement utilisées.

Donc je propose de générer les configs allyes et allno à part, et ensuite d'utiliser la commande : 
`./tuxml.py /path/to/sources -d allyes.config` (ou allno.config)

Je ferme cette issue
