### ISSUE TITLE
Configuration (infinite loop)

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#16]
* **FICHIER AFFECTÉ :**
unable to compile

* **VERSION DU FICHIER :**
---
* **VERSION DE PYTHON :** 
> 3
* **ARCHITECTURE DE LA MACHINE :**
  * Distribution : Debian
  * Noyau : 4.13.3
  * Architecture CPU : x86
* **COMMANDE EXÉCUTÉE :**
tuxml
* **OUTPUT DE LA COMMANDE :**
* **COMPORTEMENT ATTENDU :**
* **PASTEBIN VERS LE .CONFIG :**
https://gist.github.com/FAMILIAR-project/ab268ffe1f518cd2cb5f2d9a7a679d97
* **PASTEBIN VERS LE ERR.LOGS :**
https://gist.github.com/FAMILIAR-project/ab268ffe1f518cd2cb5f2d9a7a679d97

Seems related to the "famous" configuration issue https://github.com/TuxML/ProjetIrma/issues/3

We need to fix this infinite loop problem
(de manière générale j’ai l’impression qu’il faudrait envoyer en “live” le plus d’informations possibles au serveur SQL... histoire de garder trace des expériences (de la recherche de package aux configurations considérées)... en gros: plus de logs et ne pas attendre la fin de la commande pour envoyer
après pour éviter la boucle infinie peut-être faut-il poser un timeout ou un compteur... autre piste: quand on a essayé d’installer le même package plusieurs fois, ça sent la boucle infinie donc peut-être faut-il stopper. Idem sur un package “vide” à installer: ça sent la boucle infinie, il faut en sortir)

And perhaps this configuration is really faulty

**Comment by FAMILIAR-project** [comment]
Another faulty configuration 
(I have better logs: https://gist.github.com/FAMILIAR-project/52b552cc83251b9619ae8f1132645064)

**Comment by micleb** [comment]
Du coup j'ai recompilé avec le .config (premier post) que vous avez donné et... ça a crashé au bout d'une heure de compilation.

aicdb.h toujours et encore en cause

**Comment by FAMILIAR-project** [comment]
OK intéressant...  @micleb quand tu dis qu'il "crash" tu sais comment et pourquoi? 

Ce qui paraît intéressant dans cette configuration c'est qu'elle est peut-être défectueuse. Il ne faut pas oublier qu'un des objectifs du projet c'est est aussi de trouver des configurations qui ne compilent pas ;) 

Après il y a certainement un "workaround" et l'installation d'un package pour s'en sortir... A creuser

**Comment by micleb** [comment]
C'est la même histoire que d'habitude.
La compilation s'arrête car le fichier aicdb.h est manquant.
Le programme analyse les logs et tente de faire "apt-file search aicdb.h" sauf que cette commande ne renvoie rien du tout.

```
Traceback (most recent call last):
  File "./core/tuxml.py", line 215, in <module>
    status = compile()
  File "./core/tuxml.py", line 142, in compile
    return log_analysis() - 1
  File "./core/tuxml.py", line 105, in log_analysis
    status = install_missing_packages(missing_files, missing_packages)
  File "./core/tuxml.py", line 59, in install_missing_packages
    pkgs = tdep.build_dependencies_debian(missing_files);
  File "/home/micleb/Documents/ProjetIrma/core/tuxml_depman.py", line 46, in build_dependencies_debian
    output = subprocess.check_output([cmd_search.format(mf)], shell=True)
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['apt-file search  aicdb.h']' returned non-zero exit status 1
```

Déjà je vais mettre un try/except autour de la commande qui pose problème (subprocess.checkoutput), ça évitera le crash.
> If the return code was non-zero it raises a CalledProcessError.
https://docs.python.org/2/library/subprocess.html#subprocess.check_output

**Comment by FAMILIAR-project** [comment]
Oui... et ça ne me choquerait pas plus que ça que la configuration en question soit "labelisée" comme une "erreur" dans la base de données. Le fait d'éviter le crash est donc nécessaire pour envoyer les données ;)

**Comment by micleb** [comment]
Je ferme aussi cette issue (voir #16)
