### ISSUE TITLE
Sending results in the database takes too much time (unnecessarily I guess)

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#167]
Sending results to the database can take a while...
despite the fact the content is already in the database, it blocks here:

```
00:08:32 [2019-07-03 09:33:40 CEST] [insert_result_into_database] Sending result to database.
```

(a few minutes)

and then:
```
Traceback (most recent call last):
  File "/TuxML/compilation/main.py", line 212, in <module>
    config_file=args.config
  File "/TuxML/compilation/main.py", line 128, in run
    boot_result
  File "/TuxML/compilation/main.py", line 170, in insert_result_into_database
    cid = insert_and_fetch_compilation(connection, cursor, compilation)
  File "/TuxML/compilation/database_management.py", line 111, in insert_and_fetch_compilation
    __select_one_field_where_database(cursor, 'cid', 'compilations', compilation)
  File "/TuxML/compilation/database_management.py", line 54, in __select_one_field_where_database
    cursor.execute(query_select, value)
  File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 312, in _query
    db.query(q)
  File "/usr/local/lib/python3.5/dist-packages/MySQLdb/connections.py", line 224, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')
Password:
Your tamago... database Irma_db ate 1 compilations data, come back later to feed it!
Total number of container used : 1
Number of compilations in a container : 1 ( 1 basic compilation + 0 incremental compilations).
Total number of compilations : 1
```

without providing the cid

**Comment by FAMILIAR-project** [comment]
`python3 kernel_generator.py --tiny --linux4_version 15 1`

vmacher:ProjetIrma macher1$ git checkout
Your branch is up to date with 'origin/dev'.

same observation for 4.13.3

**Comment by FAMILIAR-project** [comment]
Using `python3 kernel_generator.py --linux4_version 15 --config /Users/macher1/Documents/SANDBOX/linuxevo/linux-4.15/.config`
outputs the cid

`00:09:03 [2019-07-03 10:30:31 CEST] [insert_result_into_database] Sending result to database.
00:11:01 [2019-07-03 10:32:29 CEST] [insert_result_into_database] Successfully send result with cid : 63661`

but we can notice it's taking time (2') for apparently nothing

**Comment by psaffray** [comment]
This is a problem we've observed only recently, since the database is now quite big. It actually comes from an SQL SELECT FROM WHERE query that is used to retrieve the cid of the compilation after it has been done. This query is really big, for it compares every field of the table. As the database grows up, now it takes much time to complete...

**Comment by mipicard** [comment]
I will take a look at it asap, in order to try to reduce the workload.

**Comment by mipicard** [comment]
As observed, it was a mistake from my side, not giving enough credit to cursor.lastrowid attribute. It should be fix with commit https://github.com/TuxML/ProjetIrma/commit/0ba277057dea2afc0a81a7c2f8c85a995396456a .
I will close this issue and let @psaffray rebuild the dev image tomorrow, dont hesitate to reopen if it didn't work like it should.
