### ISSUE TITLE
Checking boot: default or not?

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#168]
The following command `python3 kernel_generator.py --linux4_version 15 --config /Users/macher1/Documents/SANDBOX/linuxevo/linux-4.15/.config`

checks the boot
so by default the value seems true: https://github.com/TuxML/ProjetIrma/blob/dev/kernel_generator.py#L234-L238

how to deactivate boot?

**Comment by psaffray** [comment]
If you forgot the --dev option, then the default image used is "prod" which does not contain our latest features, like the boot deactivation. The "prod" image is still the one we had at the end of this year's project

**Comment by FAMILIAR-project** [comment]
right, --dev should be used!
