### ISSUE TITLE
Configuration (infinite loop, bis)

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#17]
* **FICHIER AFFECTÉ :**
* **VERSION DU FICHIER :**
---
* **VERSION DE PYTHON :**
* **ARCHITECTURE DE LA MACHINE :**
  * Distribution :
  * Noyau :
  * Architecture CPU :
* **COMMANDE EXÉCUTÉE :**

Same as previously: tuxml tries to install an empty package... tuxml tries at the infinite 

The err.logs 

/bin/sh: 1: as68k: not found
make[3]: *** [drivers/net/wan/wanxlfw.inc] Error 127
make[2]: *** [drivers/net/wan] Error 2
make[1]: *** [drivers/net] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [drivers] Error 2

* **OUTPUT DE LA COMMANDE :**
* **COMPORTEMENT ATTENDU :**
* **PASTEBIN VERS LE .CONFIG :**
* **PASTEBIN VERS LE ERR.LOGS :**

https://gist.github.com/FAMILIAR-project/5a3f9e495d7a8723e394fe815eb02741

(btw we need to use "log" extension -- it is more standard than "logs")

**Comment by alemasle** [comment]
Avez-vous essayé en lançant la commande MLfood.py et donc l'utilisation des Dockers ?

**Comment by FAMILIAR-project** [comment]
Non c'est la prochaine étape ;) 
mais est-ce que cela va vraiment résoudre le problème de la boucle infinie?

**Comment by alemasle** [comment]
Le fait que tous les scripts ont été écrit pour fonctionner sur l'image docker Debian, c'est possible, mais je ne peux pas l'affirmer ! Mais à chaque fois que j'ai lancé les compilations je suis passé par MLfood et donc par les Dockers pour éviter justement les problèmes du à l'OS utilisé.

**Comment by FAMILIAR-project** [comment]
Plutôt impressionné par le mécanisme auto-correctif pour charger les "packages"... 
Il a bouclé sur le même fichier défectueux plusieurs fois, mais il a réussi à installer un bon package au final. 
Et il a recommencé sur un autre. 

Je maintiens qu'il faut absolument "logger" cette étape

**Comment by micleb** [comment]
```
[*] 2017-12-14 18:03:34 | Compilation in progress
[*] 2017-12-14 18:11:11 | Compilation failed, exit status : 2
[*] 2017-12-14 18:11:11 | Analyzing error log file
[+] 2017-12-14 18:11:11 | Missing package(s) found
[+] 2017-12-14 18:11:11 | Finding package manager
[#] 2017-12-14 18:11:11 | Package manager is apt-get
[#] 2017-12-14 18:11:11 | Debian based distro
[#] 2017-12-14 18:11:11 | Those files are missing :
    as68k
[-] 2017-12-14 18:11:16 | Unable to find the missing package(s)
[-] 2017-12-14 18:11:16 | Unable to compile using this config or another error happened
[*] 2017-12-14 18:11:16 | Sending config file and status to database
[-] 2017-12-14 18:11:17 | Can't send info to db : Data too long for column 'error' at row 1
```

Même situation que sur l'autre issue #16 sauf que cette fois-ci j'ai mis un try/except autour de la ligne qui posait problème. Donc plus de crash :)
Par contre il n'a pas voulu envoyer les infos à la BDD car le fichier err.log est trop long. Peut être une config à faire du côté de sendDB pour régler ça (@PLeLuron )

EDIT : @PLeLuron a mis à jour la BDD. J'ai refais la compilation et l'envoie s'est bien passé ;-)

**Comment by micleb** [comment]
Le problème semble être corrigé, il n'y a plus de crash ou de boucle infinie

Je ferme donc cette issue ainsi que la #16
