### ISSUE TITLE
sizes when build fails (database) 

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#173]
A subtle bug: when build fails (compiled_kernel_size = -1), the compressed sizes are all to -1 (nice!) but the names of the sizes slightly differ: `GZIP-bzimage` instead of `GZIP-bzImage`(note the uppercase for `Image`) 

it's not a critical bug

**Comment by psaffray** [comment]
https://github.com/TuxML/ProjetIrma/blob/dev/compilation/compiler.py#L44-L51
I think it comes from here, it can be changed in a future build/push of the image

**Comment by FAMILIAR-project** [comment]
Indeed, you spot the inconsistency, very nice!

**Comment by psaffray** [comment]
Solved
