### ISSUE TITLE
Encoding issues / Messages in English 

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#18]
File "MLfood.py", line 75
SyntaxError: Non-ASCII character '\xc3' in file MLfood.py on line 75, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

print("Recuperation dernière version de l'image " + images[i % len(images)])

In general we should avoid french messages. 
It will allow us to avoid the non-ASCII issues ;)

**Comment by alemasle** [comment]
My fault, i am ashamed about it.
J'ai l'habitude de ne jamais écrire d'accent par réflexe, mais il semblerait que celui ci ait filtré
