### ISSUE TITLE
Full Dockerisation

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#19]
Niveau installation c'est très "simple": 
git clone https://github.com/TuxML/ProjetIrma.git
cd ProjetIrma 
git checkout dev 
sudo ./MLfood.py 1 

mais ne pourrait-on pas faire encore plus simple? 

L'idée serait simplement de récupérer une image Docker tuxml et de la lancer avec la dernière version de MLfood pré-installée ;)

**Comment by CaptainMexiko** [comment]
Ce serait intéréssant, mais il faut avoir la verison finale de MLfood.

**Comment by alemasle** [comment]
En faite c'est exactement ce que j'explique dans le README, il suffit simplement de télécharger le fichier MLfood.py et de l'exécuter, et ce script se charge de tout, il télécharge la dernière image, créé le dossier de Logs et lance les dockers tout en en sortant les Logs! 
Tout est déjà prévu!

**Comment by alemasle** [comment]
Donc si on simplifie encore l'installation se résume à : 
- Télécharger MLfood.py
./MLfood.py 1

C'est tout !

**Comment by alemasle** [comment]
Pour une utilisation "utilisateur" le simple script MLfood.py est nécessaire pour lancer des compilations.

TPDIM.py est nécessaire seulement pendant la phase de programmation et de préparation afin de reconstruire l'image docker lors de changement dans le code des scripts intra image Docker tuxmldebian.

**Comment by ghost** [comment]
Après je prévois que TPDIM permettent la création d'image, de pouvoir gérer les dockers et de mettre en ligne sur des repo perso, bref de ne pas avoir à toucher au commande de docker qui sont un peu compliqué à utiliser.

**Comment by FAMILIAR-project** [comment]
@alemasle merci beaucoup pour ces explications, j'avais loupé en effet ce cas d'usage... (je pensais que MLfood.py était dépendant des autres scripts du repo...) 

Ceci étant il faut quand même faire un git clone et récupérer le fichier...
J'aimerais vraiment donner une et une seule commande, ou du moins manipuler qu'une seule entité... 

peut-être 
docker pull tuxml/tuxmldebian:latest et un docker run dans la foulée (MLfood étant embarqué dans l'image) 

Mon cas d'usage c'est de motiver une cinquantaine de collègues à tester notre solution... 
Si je peux leur filer une seule commande c'est parfait ;-) 

En l'état remarque on peut s'en sortir ainsi:

wget https://raw.githubusercontent.com/TuxML/ProjetIrma/dev/MLfood.py
python3 MLfood.py 1

(droits du "sudo" demandés après)

**Comment by alemasle** [comment]
étant donné qu'il n'y a qu'une seule commande à lancer ( ./MLfood.py 1 ) il faudrait effectivement éviter d'avoir à cloner tout le repository contenant tous les fichiers. De plus MLfood.py se trouve dans l'image docker mais n'as aucune utilité à se trouver à l'intérieur ( Elle y est seulement car elle se trouve dans le même repository ) ce qu'on peut faire c'est de créer un autre repository à coté ne contenant que MLfood.py.

Avec ça il suffira de lancer les commandes : 

git clone github.com/repository_MLfood/
cd repository_MLfood/
./MLfood 1 

et le tour est joué !

On aura bien une simple commande sans s'encombrer des autres fichiers pour rien. 
Un fichier unique pour tous les gouverner et dans les dockers les lier.

**Comment by alemasle** [comment]
ça vous convient de créer un repository contenant seulement MLfood.py qui sera du coup le seul fichier à télécharger et exécuter sur une machine ?

**Comment by FAMILIAR-project** [comment]
@alemasle peut-être qu'on peut utiliser la notion de "release" de Github? 
https://help.github.com/articles/creating-releases/

plus propre que la création d'un repo dédié

**Comment by Heartbroken-Git** [comment]
Effectivement, si on a une version qui marche du projet il faudra utiliser
les tags et les Releases pour mettre à disposition une version "propre"
pour un utilisateur. C'est exactement pour ça que c'est fait :)

**Comment by alemasle** [comment]
Oui mais la release ne change pas le fait que tout le projet serais téléchargé alors qu'il suffirait de télécharger seulement le script MLfood.py.

**Comment by Heartbroken-Git** [comment]
Bien sûr que non sinon les Releases auraient aucun intérêt. C'est toi qui
choisis ce que tu mets à disposition dans la release. Et tu peux par
exemple juste mettre le script Python.

L'utilisateur aura alors la possibilité de DL juste le script ou tout le
code source s'il le souhaite.

**Comment by alemasle** [comment]
D'accord ! Je vais essayer de faire une release du script MLfood.py dans ce cas !

**Comment by Heartbroken-Git** [comment]
Cf le repo d'ACO d'@Aexelion et moi pour voir un exemple de comment on
utilise les Releases pour limiter la distribution des versions du
Mini-Editeur. ;)

**Comment by FAMILIAR-project** [comment]
Oui c'est cela (même si la "doc" en première lecture n'est pas très explicite) 
Bon courage ;)

**Comment by alemasle** [comment]
Une release ayant été crée je clos l'issue
