### ISSUE TITLE
Utilisation Image système à jour

### ISSUE THREAD

**Issue by alemasle** [TuxML/ProjetIrma#2]
Le script `MLfood.py` a besoin d'une image système à jour.

Il nous faudrait un script qui rebuild la nouvelle image système (debian) avec la dernière version de `tuxml.py` et des autres scripts dépendant.

Le script `MLfood.py`utilise une image qui sera la dernière en ligne, cette image devra être mise à jour à chaque mise à jour de `tuxml.py`. D'où un script de build et push de l'image automatiquement après chaque changement.

Merci.

**Comment by Heartbroken-Git** [comment]
@micleb Je te laisse voir qui dans l'équipe est dispo pour bosser dessus et l'assigner à l'issue ;)

PS : Je l'ai pas assigné au Milestone en cours comme c'est une *feature request* mais n'hésite pas à le faire si tu pense que ça peut être un bon ajout pour l'objectif en cours.

**Comment by micleb** [comment]
C'est Gwendal qui s'en occupe

**Comment by ghost** [comment]
J'ai rajouté le script autoDocker.py qui permet de répondre de façon basique à la demande. Le script doit ètre lancé manuellement après chaque changement dans py-scripts.
