### ISSUE TITLE
All configuration options in CSV headers

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#21]
Bonjour, 

A partir de fichiers .config (dans la base de données), on souhaite construire un CSV tel que:
 * les colonnes sont les options de configurations
 * chaque ligne est une configuration (un .config)
 * les valeurs des cellules sont "y", "n", ou "m" 

Dans un .config, quand une option n'est pas présente et renseignée, c'est qu'elle est à "n". 
On a donc besoin de connaître toutes les options possibles pour un kernel Linux donné. L'information n'étant pas présente dans un .config, il faut aller la chercher ailleurs. 

Pour l'instant, on a appliqué la stratégie suivante: on a pris allyes.config et on a supposé que cette configuration contenait toutes les options possibles du kernel Linux. 
C'est IMHO faux. 
Pour deux raisons. La première, théorique, c'est qu'il y a des contraintes entre options, dont des contraintes mutuellement exclusives. Par construction, on ne peut pas créer une configuration avec deux options mutuellement exclusives, et donc le allyes.config ne contiendra pas nécessairement une des deux. 
La deuxième, c'est l'étude de l'algo du allyesconfig. 
Une implémentation en Python est disponible ici:
https://github.com/ulfalizer/Kconfiglib/blob/master/examples/allyesconfig.py 
et l'auteur a montré que la procédure produit le même résultat que la commande écrit en C (on pourrait aller regarder le code C de allyesconfig, mais c'est moins lisible et compréhensible). 
Si on étudie l'algo. on voit bien qu'il est glouton: il essaie de mettre le maximum d'options à "y" ou "m". Mais certains sont assignés à "n" du fait des sélections précédentes: 
https://github.com/ulfalizer/Kconfiglib/blob/master/kconfiglib.py#L2533 

En résumé: **allyes.config ne contient pas toutes les options du kernel Linux.** 

On pourrait d'ailleurs le démontrer par l'expérience. Voici comment.
Si on regarde allyes.config 
vmacher:csvgen macher1$ cat allyes.config | wc -l
   11135
Si on regarde le CSV généré à partir de 200 .configs de la base de données: 
ncol(res)
[1] 9641

A terme, je m'attends à avoir plus de colonnes dans le CSV que d'options dans le allyes.config 
On pourrait générer des milliers de .config (sans les compiler évidemment) comme je l'avais demandé ici https://github.com/TuxML/ProjetIrma/issues/10. Ensuite on vérifie qu'il y a bien des options à "y" dans un des .config qui n'apparaissent pas dans allyes.config 

Il va donc falloir trouver une autre solution pour trouver toutes les options du kernel Linux. 
Une solution brutale mais nécessairement incomplète est de faire l'union des options à "y" et "m" sur des millions de fichiers .config
Il y a une solution plus complète et potentiellement moins coûteuse: il suffit simplement d'analyser les fichiers KConfig du kernel Linux et de collecter toutes les options déclarées. 
Problème: il faut "parser" de tels fichiers et analyser leur contenu. 
Heureusement il y a une solution très prometteuse avec cette librairie... Python qui semble de bonne qualité et maintenue: https://github.com/ulfalizer/Kconfiglib/ 

Le plan d'action concret est d'utiliser cette librairie pour collecter toutes les options. On pourra notamment adapter ce code: https://github.com/ulfalizer/Kconfiglib/blob/master/examples/print_tree.py

**Comment by FAMILIAR-project** [comment]
Par rapport à mes explications, il y a une erreur et précision importante
vmacher:csvgen macher1$ wc -l allyes.config 
   11135 allyes.config

est naïf car il y a des commentaires et des sauts de ligne qu'il ne faut évidemment pas compter comme des options. 

Une rapide procédure Python qui "parse" montre qu'il y a en fait **9542** options. 
Or il existe 9641 colonnes dans le CSV de "test"... Il y a bien une centaine d'options dans les .config, non exprimée dans le "allyes.config"

**Comment by FAMILIAR-project** [comment]
démonstration avec un petit programme Python qui compare les options de 10 .config (random) avec le allyes.config: 

options missing in allyes  ['CONFIG_BROKEN_ON_SMP', 'CONFIG_TINY_RCU', 'CONFIG_TINY_SRCU', 'CONFIG_DEFAULT_DEADLINE', 'CONFIG_UP_LATE_INIT', 'CONFIG_NEED_PER_CPU_KM', 'CONFIG_ACPI_CUSTOM_DSDT_FILE', 'CONFIG_MTD_BLOCK_RO', 'CONFIG_I2C_ALGOPCF', 'CONFIG_SSB_DEBUG', 'CONFIG_USB_DWC3_HOST', 'CONFIG_USB_ISP1760_HOST_ROLE', 'CONFIG_ADXL345', 'CONFIG_ADXL345_I2C', 'CONFIG_ADXL345_SPI', 'CONFIG_IIO_ST_ACCEL_3AXIS', 'CONFIG_IIO_ST_ACCEL_I2C_3AXIS', 'CONFIG_IIO_ST_ACCEL_SPI_3AXIS', 'CONFIG_TI_ADS1015', 'CONFIG_DEFAULT_SECURITY_DAC', 'CONFIG_HZ_PERIODIC', 'CONFIG_VMAP_STACK', 'CONFIG_X86_DIRECT_GBPAGES', 'CONFIG_SSB_DEBUG', 'CONFIG_HZ_PERIODIC', 'CONFIG_GCC_PLUGINS', 'CONFIG_GCC_PLUGIN_CYC_COMPLEXITY', 'CONFIG_GCC_PLUGIN_SANCOV', 'CONFIG_GCC_PLUGIN_LATENT_ENTROPY', 'CONFIG_GCC_PLUGIN_STRUCTLEAK', 'CONFIG_GCC_PLUGIN_STRUCTLEAK_VERBOSE', 'CONFIG_X86_DIRECT_GBPAGES', 'CONFIG_I2C_ALGOPCF', 'CONFIG_ADXL345', 'CONFIG_ADXL345_I2C', 'CONFIG_IIO_ST_ACCEL_3AXIS', 'CONFIG_IIO_ST_ACCEL_I2C_3AXIS', 'CONFIG_INA2XX_ADC', 'CONFIG_DEBUG_INFO', 'CONFIG_DEBUG_INFO_DWARF4', 'CONFIG_DEFAULT_SECURITY_DAC', 'CONFIG_HZ_PERIODIC', 'CONFIG_GCC_PLUGINS', 'CONFIG_VMAP_STACK', 'CONFIG_USB_KBD', 'CONFIG_USB_MOUSE', 'CONFIG_USB_DWC2_HOST', 'CONFIG_IIO_ST_ACCEL_3AXIS', 'CONFIG_IIO_ST_ACCEL_I2C_3AXIS', 'CONFIG_ROMFS_BACKED_BY_MTD', 'CONFIG_ROMFS_ON_MTD', 'CONFIG_DEBUG_INFO', 'CONFIG_DEBUG_INFO_SPLIT', 'CONFIG_DEBUG_INFO_DWARF4', 'CONFIG_GDB_SCRIPTS', 'CONFIG_X86_DECODER_SELFTEST', 'CONFIG_DEFAULT_SECURITY_DAC', 'CONFIG_HZ_PERIODIC', 'CONFIG_TRIM_UNUSED_KSYMS', 'CONFIG_DEFAULT_DEADLINE', 'CONFIG_X86_DIRECT_GBPAGES', 'CONFIG_ACPI_CUSTOM_DSDT_FILE', 'CONFIG_GIGASET_I4L', 'CONFIG_I2C_ALGOPCF', 'CONFIG_NTP_PPS', 'CONFIG_IIO_ST_ACCEL_3AXIS', 'CONFIG_IIO_ST_ACCEL_I2C_3AXIS', 'CONFIG_DEFAULT_SECURITY_TOMOYO', 'CONFIG_HZ_PERIODIC', 'CONFIG_VMAP_STACK', 'CONFIG_DEFAULT_DEADLINE', 'CONFIG_INLINE_SPIN_UNLOCK_IRQ', 'CONFIG_INLINE_READ_UNLOCK', 'CONFIG_INLINE_READ_UNLOCK_IRQ', 'CONFIG_INLINE_WRITE_UNLOCK', 'CONFIG_INLINE_WRITE_UNLOCK_IRQ', 'CONFIG_X86_DIRECT_GBPAGES', 'CONFIG_USB_DWC3_HOST', 'CONFIG_USB_DWC2_HOST', 'CONFIG_USB_ISP1760_HOST_ROLE', 'CONFIG_INA2XX_ADC', 'CONFIG_SECURITY_TOMOYO_POLICY_LOADER', 'CONFIG_SECURITY_TOMOYO_ACTIVATION_TRIGGER', 'CONFIG_DEFAULT_SECURITY_TOMOYO', 'CONFIG_VMAP_STACK', 'CONFIG_X86_DIRECT_GBPAGES', 'CONFIG_DEFAULT_CDG', 'CONFIG_ADXL345', 'CONFIG_ADXL345_I2C', 'CONFIG_IIO_ST_ACCEL_3AXIS', 'CONFIG_IIO_ST_ACCEL_I2C_3AXIS', 'CONFIG_TI_ADS1015', 'CONFIG_DEFAULT_SECURITY_DAC', 'CONFIG_BROKEN_ON_SMP', 'CONFIG_TINY_RCU', 'CONFIG_TINY_SRCU', 'CONFIG_GCC_PLUGINS', 'CONFIG_GCC_PLUGIN_CYC_COMPLEXITY', 'CONFIG_GCC_PLUGIN_SANCOV', 'CONFIG_VMAP_STACK', 'CONFIG_UP_LATE_INIT', 'CONFIG_NEED_PER_CPU_KM', 'CONFIG_GPIO_BT8XX', 'CONFIG_DRM_I915_WERROR', 'CONFIG_USB_MUSB_HOST', 'CONFIG_USB_DWC2_HOST', 'CONFIG_ADXL345', 'CONFIG_ADXL345_I2C', 'CONFIG_ADXL345_SPI', 'CONFIG_XFS_WARN', 'CONFIG_DEFAULT_SECURITY_DAC', 'CONFIG_BROKEN_ON_SMP', 'CONFIG_HZ_PERIODIC', 'CONFIG_TINY_RCU', 'CONFIG_TINY_SRCU', 'CONFIG_VMAP_STACK', 'CONFIG_UP_LATE_INIT', 'CONFIG_NEED_PER_CPU_KM', 'CONFIG_SSB_DEBUG', 'CONFIG_MFD_SUN4I_GPADC', 'CONFIG_ADXL345', 'CONFIG_ADXL345_SPI', 'CONFIG_TI_ADS1015', 'CONFIG_DEFAULT_SECURITY_DAC', 'CONFIG_BROKEN_ON_SMP', 'CONFIG_HZ_PERIODIC', 'CONFIG_TINY_RCU', 'CONFIG_TINY_SRCU', 'CONFIG_UP_LATE_INIT', 'CONFIG_NEED_PER_CPU_KM', 'CONFIG_I2C_ALGOPCF', 'CONFIG_GPIO_BT8XX', 'CONFIG_MFD_SUN4I_GPADC', 'CONFIG_IIO_ST_ACCEL_3AXIS', 'CONFIG_IIO_ST_ACCEL_I2C_3AXIS', 'CONFIG_SUN4I_GPADC', 'CONFIG_KMEMCHECK', 'CONFIG_KMEMCHECK_ONESHOT_BY_DEFAULT', 'CONFIG_KMEMCHECK_QUEUE_SIZE', 'CONFIG_KMEMCHECK_SHADOW_COPY_SHIFT', 'CONFIG_KMEMCHECK_PARTIAL_OK', 'CONFIG_KMEMCHECK_BITOPS_OK', 'CONFIG_DEFAULT_SECURITY_DAC', 'CONFIG_CRYPTO_FIPS']

144 options non exprimés dans allyes.config 

confirmation qu'il faut explorer une autre alternative pour récupérer toutes les options

**Comment by FAMILIAR-project** [comment]
se positionner dans le répertoire csvgen/ 
puis générer les config (avec make random et en spécialisant sur l'archi X86_64)
sh generRandconfig.sh /Users/macher1/Documents/SANDBOX/allyesklinux/linux-4.13.3
($1 pour spécifier les sources Linux)

python3 collectAllOptions.py (pour identifier les options non présentes dans allyes)
python3 csvGenerator.py > res2.csv (pour construire le CSV des configs)

**Comment by FAMILIAR-project** [comment]
Btw ce serait marrant de montrer qu'avec l'aléatoire et make randconfig on arriverait à trouver une configuration qui contient plus de "y" que allyes.config ;-)

**Comment by FAMILIAR-project** [comment]
La question a été posée à la soutenance: combien il y a d'options dans le kernel Linux? 

Pour y répondre, il suffit d'utiliser Kconfiglib: 
"Le plan d'action concret est d'utiliser cette librairie pour collecter toutes les options. On pourra notamment adapter ce code: https://github.com/ulfalizer/Kconfiglib/blob/master/examples/print_tree.py"

@PLeLuron tu prends ?

**Comment by ghost** [comment]
Je suis dessus

**Comment by FAMILIAR-project** [comment]
$ make ARCH=x86 PYTHONCMD=python3 scriptconfig SCRIPT=Kconfiglib/examples/print_tree.py | grep config | wc -l
12799

si t'as une petite doc sur comment lancer cette commande je suis preneur ;)

**Comment by ghost** [comment]
Alors dans le kernel :
`git clone git://github.com/ulfalizer/Kconfiglib.git`
`git am Kconfiglib/makefile.patch`

**Comment by FAMILIAR-project** [comment]
et pas besoin de spécifier où se situent les sources du kernel? 
car on voudrait les chiffres sur la 4.13.3 par exemple (ou une autre)

**Comment by ghost** [comment]
Il faut le faire directement dans les sources du kernel, le patch va affecter le makefile du kernel ce qui ajoute la cible `scriptconfig`

**Comment by ghost** [comment]
le script de https://github.com/TuxML/csvgen permet maintenant de générer un fichier CSV valide qui contient les noms, les types, et les valeurs des configurations pour chaque propriété du .config + la taille du kernel et le temps de compilation.
