### ISSUE TITLE
Collecter un maximum d'informations sur le "contexte" de la compilation (caractéristiques de la machine utilisée, du compilateur utilisé, etc.) 

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#23]
Lors de la compilation du kernel, on va mesurer différentes propriétés quantitatives (eg temps pour compiler le kernel). 
Il est intéressant de collecter un maximum d'informations sur comment on a compilé le kernel. 
On va typiquement utiliser différentes machines, avec probablement des compilateurs différents (gcc 3.X ou 4.Y), des CPUs différents, etc. 

Une liste non-exhaustive des informations à collecter:
 * caractéristiques hardware de la machine (type de CPU, RAM, nombre de coeurs (utilisés et à disposition))  
 * caractéristiques du compilateur gcc, quelle version de la libc, etc. 
 * caractéristiques de l'OS: Debian oui, mais quelle distribution spécifiquement? quelle version du kernel? pourquoi pas une liste des packages déjà installés sur la machine

Ce serait intéressant également de mesurer le temps CPU moyen. 

# Pourquoi collecter toutes ces informations? 

Il est probable que les caractéristiques du contexte influencent certaines propriétés quantitatives. Avec une machine très puissante, je vais peut-être compiler mon kernel en 5 minutes alors qu'un autre utilisateur va mettre 30 minutes sur la même configuration car il a utilisé peu de coeurs et il a de toute façon une machine peu puissante. 

En fait, c'est une vraie question de recherche: est-ce qu'à configuration du kernel "constante" on observe de grosses variations à cause de la machine utilisée pour la compilation? 
Si oui, quelles sont les caractéristiques qui influent le plus? 

On va pouvoir répondre à cette question, à condition de... collecter davantage d'informations. 

# Comment l'implémenter? 

Il va falloir implémenter (si possible réutiliser) des outils/scripts qui collectent ce genre d'information. 
La liste est non-exhaustive, et elle va très certainement évoluer. 
Aussi la solution qui consiste à créer autant de champs dans la base de données qu'il y a d'informations à collecter me paraît un "overkill". 
Je préconise de "logger" ces informations dans un ou plusieurs fichiers plus ou moins structurés. 
On aura un champ "machine_information" capable d'accueillir ces fichiers. 
Ensuite on écrira une procédure capable d'analyser ces fichiers et les organiser correctement dans un CSV typiquement. 

# Liste non-exhaustive 

Ne pas hésiter ici à compléter la liste

**Comment by FAMILIAR-project** [comment]
Très bête mais il faut absolument envoyer la version de TuxML/MLfood utilisée (pour faciliter la reproductibilité...)

**Comment by alemasle** [comment]
Dans ce cas c'est la version de TuxML qu'il faut envoyer sachant que MLfood ne touche pas aux données de compilation

**Comment by BzhErlb** [comment]
J'ai fais une première version (tuxml_environment.py), **il faudrait que quelqu'un sous Debian et Ubuntu testent sur leur environnement pour voir si c'est suffisamment portable et fonctionnel**. Normalement ça devrait l'être. 

J'ai testé sous Archlinux et ça m'a l'air cohérent, j'ai juste la version de la distrib qui est une chaîne vide mais comme Arch est une rolling release je pense que c'est normal.

Les 3 méthodes get_xyz() renvoient les infos sous formes de table de hachage (les "dictionnaires" en python) pour retrouver facilement les infos si besoin (par exemple hw = get_hardware() puis hw["ram"] nous donne la quantité de RAM).
Il y a aussi une méthode d'exportation qui sauvegarde tout d'un coup dans un seul fichier csv.

**Est-ce qu'il nous faut aussi une méthode pour passer d'un fichier csv à un dictionnaire python ?**

Il manque encore la liste des paquets déjà installés.
Faudrait sûrement aussi logger les noms des paquets manquant installés suite à l’analyse de log pour visualiser rapidement ceux qui apparaissent de manière récurrente.

On peut facilement ajouter plein d'infos, reste à voir qu’est-ce qui est pertinent ou inutile.
Je pense à des trucs comme la mémoire libre, la fréquence/latence de la ram, la quantité de cache pour le CPU et si l'on compile on sur un SSD ou pas/si l'on swap ou pas. 

Il faudrait aussi un moyen de récupérer la version de TuxML, pour l'instant c'est codé en dur dans tuxml.py.

**Comment by micleb** [comment]
Excellent !
J'ai testé sur Arch et tout est bon : 
```
{'os': 'Linux', 'distribution': 'arch', 'distib_version': '', 'kernel': '4.13.15-1-hardened'}
{'cpu': ' Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz', 'cpu_freq': ' 2893', 'ram': '8098672', 'arch': 'x86_64', 'cpu_cores': 4}
{'libc_version': '2.26', 'gcc_version': '7.2.0', 'core_used': 1}
```

Par contre sur mon serveur Debian ça a planté :-/
Hier ça marchait super bien, quoi qu'il en soit les valeurs des 2 premières lignes sont correctes
```
{'distribution': 'debian', 'os': 'Linux', 'kernel': '4.9.0-3-amd64', 'distib_version': '9.1'}
{'cpu_cores': 8, 'arch': 'x86_64', 'cpu_freq': ' 1999', 'cpu': ' Intel(R) Xeon(R) CPU           E5405  @ 2.00GHz', 'ram': '8178820'}
Traceback (most recent call last):
  File "./core/tuxml_environment.py", line 110, in <module>
    print(get_compilation_details())
  File "./core/tuxml_environment.py", line 92, in get_compilation_details
    "libc_version": __get_libc_version(),
  File "./core/tuxml_environment.py", line 74, in __get_libc_version
    result = subprocess.run(["ldd", "--version"], stdout=subprocess.PIPE,encoding="UTF8").stdout
  File "/usr/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'encoding'
```

Pour récupérer la version de tuxml tu peux faire : 
`version = subprocess.check_output(["./tuxml.py -V"], shell=True)`

Et +1 pour savoir si on compile sur un HDD ou un SSD

**Comment by BzhErlb** [comment]
C'est corrigé, tu peux retester  (Ça venait de encoding="UTF8"). 
Sous ma VM (debian 9.3) et arch ça fonctionne.

**Comment by micleb** [comment]
Ca marche seulement si on est dans le répertoire /TuxML/core
Si on se place dans un autre répertoire il ne connait pas `./tuxmlpy`
Il faudrait récupérer le chemin d'exécution de tux_env.py et l'appliquer à tux.py

Autre remarque, pour la version de tuxml c'est marqué : `b'tuxml.py pre-alpha v0.2'`. Faudrait que t'encode la chaîne en UTF-8 et, avis perso, ce serait mieux d'avoir juste "pre-alpha v0.2"

Sinon ce sont les bonnes valeurs, ça marche impec' sur Arch et Debian.

**Comment by FAMILIAR-project** [comment]
Cela marche bien également ici, bravo! 

(machine Debian avec Docker) 
```
[*] 2017-12-19 12:12:22 | Getting environment details
{'distrib_version': '9.2', 'distribution': 'debian', 'os': 'Linux', 'kernel': '4.4.0-47-generic'}
{'cpu': 'AMD A10-7700K APU with Radeon(TM) R7 Graphics', 'arch': 'x86_64', 'cpu_freq': '3400', 'cpu_cores': 4, 'ram': '7151452'}
{'libc_version': '2.24-11+deb9u1)', 'core_used': 4, 'tuxml_version': 'pre-alpha v0.2', 'gcc_version': '6.3.0-18)'}
```

(machine MacOS avec Docker)
```
[*] 2017-12-19 11:51:22 | Getting environment details
{'kernel': '4.9.49-moby', 'os': 'Linux', 'distrib_version': '9.2', 'distribution': 'debian'}
{'cpu_freq': '2793', 'ram': '2046752', 'cpu': 'Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz', 'arch': 'x86_64', 'cpu_cores': 4}
{'core_used': 4, 'tuxml_version': 'pre-alpha v0.2', 'libc_version': '2.24-11+deb9u1)', 'gcc_version': '6.3.0-18)'}
```

**Comment by FAMILIAR-project** [comment]
lscpu est un utilitaire intéressant à considérer... On peut bêtement l'utiliser par un appel système (peut-être l'installer sur l'image Docker s'il n'y est pas de base)

**Comment by micleb** [comment]
J'ai des erreurs lorsque le programme essaye de récupérer le type de disque (HDD/SSD).
Sur docker ça a même crashé.

Et quelques petites coquilles se sont glissées lorsqu' @BzhErlb récupère la version de GCC et de la LibC sur Debian et Centos.
Les versions ont mal été parsées et il renvoie des charactères supplémentaires (en plus de la version)

**Comment by micleb** [comment]
Après discussion avec l'équipe on a décidé de fermer cette issue.
Si quelqu'un souhaite récupérer une nouvelle information et la sauvegarder dans l'environnement il faudra ouvrir une nouvelle issue.
