### ISSUE TITLE
Envoyer les logs à la base de données 

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#24]
Actuellement on a 3 fichiers "log" (eg err.log) qui sont créés dans un dossier local avec nom unique. 
Il est nécessaire d'envoyer ce dossier (via une archive tar?) et l'associer à une configuration dans la base de données. 
Ces logs seront très utiles pour comprendre d'éventuelles erreurs, les packages installés, etc. 

C'est dommage de les laisser en local.

**Comment by micleb** [comment]
Oui je suis d'accord, actuellement seul le fichier err.log est envoyé après la compilation (donc géré par tuxml.py). Il faudrait aussi std.log (géré lui aussi par tuxml.py)

Par contre output.log est géré par tuxlogs.py, donc on ne peut pas l'envoyé via le script sendDB étant donné que tuxlogs monitore tuxml.py qui, lui, appelle sendDB...

Je pense qu'il faudrait faire 2 requêtes vers la BDD.
1. La première, via sendDB, qui envoie les infos relative à la compilation (date, durée, config file etc). Donc elle créée une nouvelle entrée dans la BDD
2. La seconde requête se ferait à la fin du fichier tuxlogs. Il enverrait les 3 fichiers de logs. Donc il modifierait l'entrée créée précédemment en ajoutant les 3 fichiers.

**Comment by Heartbroken-Git** [comment]
Après discussion avec l'équipe j'ajoute @alemasle à l'issue car @PLeLuron est occupé avec les autres issues pour le moment.
Un débat est ouvert quand à l'intérêt de l'ajout des logs dans la base de données quand ils servent plutôt à débugger le programme.

**Comment by alemasle** [comment]
Après discussion avec @micleb MLfood.py n'a aucun logs à envoyer, si logs il faut envoyer c'est tuxml et descendants qui enverrons.

**Comment by alemasle** [comment]
Je change donc l'assignation pour cette issue pour @micleb

**Comment by micleb** [comment]
Fait, commit https://github.com/TuxML/ProjetIrma/commit/348146f67335a4cc548fc7a3b49de2b809958cf9

Il y a le fichier .config, le stdlog_file et l'errlog_file.
J'ai vu avec @alemasle que l'output.log était inutile.

Petite différence avec l'ancien script, cette fois le contenu des fichiers de logs sera encodé en base64 (j'avais quelques problèmes d'encodage)
