### ISSUE TITLE
Is sudo really needed for MLfood?

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#27]
Bonsoir, 

Si on désactive tous les "sudo" de MLfood, pourquoi cela ne marcherait-il pas? 

En fait c'est nécessaire IMHO de pouvoir lancer MLfood sans les droits root dans un scénario de déploiement sur la grille. 
Et même pour un utilisateur ce serait bien plus rassurant. 

Peut-être ai-je loupé un détail?

**Comment by alemasle** [comment]
MLfood.py se lance sans sudo mais c'est Docker qui en demande les droits pour s'exécuter, le script MLfood.py se débrouille sans sur tout le long de son exécution jusqu'au moment de l'exécution des Dockers qui nécessites les droits super-utilisateurs car sans eux nous avons une permission denied.

**Comment by FAMILIAR-project** [comment]
@alemasle pas le cas de mon côté a priori 

peut-être sur les machines que j'utilise ont été configurées spécifiquement 
en tout cas on le peut: 
https://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo
https://docs.docker.com/engine/installation/linux/linux-postinstall/

**Comment by micleb** [comment]
Concernant docker et mlfood je ne sais pas.

Mais du côté de tuxml.py il y aurait **peut être** une possibilité.
C'est juste une suposition, je n'ai encore rien regardé, mais peut être qu'il y a moyen de télécharger les paquets sans les installer (on télécharge les sources et on les compile).

Faut creser de ce côté là...

**Comment by alemasle** [comment]
La suppression des droits sudo est possible mais le problème vient des PCs de la fac, il faut changer les droits d'exécution du daemon docker, ce que je ne peux pas faire sur les machines de l'istic donc ça poserait des problèmes. Sachant que même la fac nous donne la permission d'utiliser sudo pour utiliser docker sur nos sessions je me demande pourquoi ils n'ont pas simplement supprimé cette restriction pour nous y donner accès si c'est possible.

**Comment by alemasle** [comment]
Je laisse l'issue en suspend, car dans notre cas nous sommes bloqué si nous voulons lancer MLfood.py sans sudo sur les pc de l'université.
