### ISSUE TITLE
Logs inconsistency between Docker and Python scripts 

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#28]
https://github.com/TuxML/ProjetIrma/blob/dev/MLfood.py#L96-L97

Il semblerait que la dernière image Docker génère encore des ".logs" (au lieu des ".log") 
En tout cas tous mes dossier dans Logs ne contiennent pas les fameux fichier std et err
Et le fichier output est a priori... vide 

Un peu relié à cette issue: 
https://github.com/TuxML/ProjetIrma/issues/24

**Comment by alemasle** [comment]
Ah il semble juste que avec la modification de Mickael sur le script tuxml.py il ait tout simplement oublié de re construire l'image avec la nouvelle version. Je m'en occupe.

**Comment by alemasle** [comment]
Les logs sont de nouveaux en correlation je clos donc l'issue
