### ISSUE TITLE
Compilation toujours ratée

### ISSUE THREAD

**Issue by alemasle** [TuxML/ProjetIrma#29]
Toutes les dernières compilation lancées termine de la même manière : 

[output.log](https://github.com/TuxML/ProjetIrma/files/1563668/output.log)

Elles se finissent toutes par l'exit status 2 et donc la compilation à échouer.

[20171215_185014.zip](https://github.com/TuxML/ProjetIrma/files/1563670/20171215_185014.zip)

Voici le fichier output.log et le .config correspondant de l'une de ces compilations.

**Comment by micleb** [comment]
Étrange, chez moi (sans docker) ça se passe bien.

Je vais essayer avec le .config et je te redis

**Comment by alemasle** [comment]
Tu es censé toujours passer par Docker pour être sur que ça fonctionne sur le même OS que les autres ( l'image Debian )

**Comment by micleb** [comment]
J'ai une debian moi aussi, avec toutes les dépendances installée.

Des fois l'image est bugguée (à cause de TPDIM ou autre), et vu que je ne peux rien faire tant que ce n'est pas réparé j'utilise la commande tuxml directement.
C'est plus rapide pour tester les modifs que j'ai fais sur les scripts.

**Comment by FAMILIAR-project** [comment]
C'est clairement l'image Docker. 
Après d'où ça vient dans l'image Docker, that is the question

**Comment by micleb** [comment]
Oui je pense aussi.

En plus ça marchait tout à l'heure, et je n'ai rien push aujourd'hui

EDIT : La compilation vient de finir sans problèmes. Je vais essayer avec l'image docker
EDIT : Je l'ai lancé sur docker, Wait & see
```
micleb@kcs : sudo docker run -it tuxml/tuxmldebian:latest bash
root@39449fc81b03: ./core/tuxml.py linux-4.13.3 -c 6 -v 2 -d issue29.config
```
Pour l'instant tout se passe bien, certains fichiers/paquets étaient manquants, la compilation est en cours

**Comment by micleb** [comment]
Ca vient d'échouer : 
```
[#] 2017-12-15 19:42:42 | Those files are missing :
    $'\r'
[-] 2017-12-15 19:42:48 | Unable to find the missing package(s)
[-] 2017-12-15 19:42:48 | Unable to compile using this KCONFIG_FILE
[*] 2017-12-15 19:42:48 | Sending config file and status to database
[+] 2017-12-15 19:42:49 | Successfully sent info to db
```

Et l'err.log : 
```
akefile:936: "Cannot use CONFIG_STACK_VALIDATION, please install libelf-dev, libelf-devel or elfutils-libelf-devel"
./.config: line 46: $'\r': command not found
make: *** [vmlinux] Error 127
```
C'est vraiment bizarre ô.O

La ligne 46 en question : 
```
    45  CONFIG_THREAD_INFO_IN_TASK=y
    46
    47  #
```

**Comment by micleb** [comment]
En faite il s'agissait d'un problème d'encodage des caractères (présence de \r utilisé par windows)
J'ai fait un `dos2unix issue29.config` et ça a fonctionné.

Problème réglé
