### ISSUE TITLE
La compilation plante lorsque le fichier aicbd.h est manquant

### ISSUE THREAD

**Issue by micleb** [TuxML/ProjetIrma#3]
* **FICHIER AFFECTÉ :** tuxml.py
* **VERSION DU FICHIER :** 0.1
---
* **VERSION DE PYTHON :** 3.5
* **ARCHITECTURE DE LA MACHINE :**
  * Distribution : Debian 9 
  * Noyau : 4.9.0.3
  * Architecture CPU : amd64
* **COMMANDE EXÉCUTÉE :** ./tuxml.py /home/micleb/Documents/TUXML/linux-4.13.3/ --debug
* **OUTPUT DE LA COMMANDE :** https://pastebin.com/raw/2tyfTN03
* **COMPORTEMENT ATTENDU :** Le programme devrait trouver le paquet manquant, l'installer et reprendre la compilation
* **PASTEBIN VERS LE .CONFIG :** KCONFIG_SEED=0xE4B204B
* **PASTEBIN VERS LE ERR.LOGS :** https://pastebin.com/raw/3WHBD4Vh

Ce n'est pas la première fois que ça m'arrive.
La commande apt-file search aibcd.h ne renvoit rien. Même sur internet je ne trouve pas d'infos concernant ce fichier

**Comment by FAMILIAR-project** [comment]
C'est aicdb.h (et non aicbd.h)
`aicasm_symbol.c:48:19: fatal error: aicdb.h: No such file or directory
 #include "aicdb.h"`

Ceci étant, je n'aide pas trop ;) 
Je regarde d'où vient ce header

**Comment by FAMILIAR-project** [comment]
cela apparaît dans “dontdiff” https://www.kernel.org/doc/Documentation/dontdiff
“dontdiff” is a list of files which are generated by the kernel during
the build process, and should be ignored in any diff(1)-generated
patch.  The “dontdiff” file is included in the kernel tree in

donc première conclusion: aicdb.h est généré par le build du kernel (ce n’est pas directement un “paquet” manquant)

on voit que “aicdb.h” est en fait le contenu de db_185.h
qui se situe dans différents dossiers
confirmation ici sur la branche “mainstream” https://github.com/torvalds/linux/blob/master/drivers/scsi/aic7xxx/aicasm/Makefile#L45-L58

et donc visiblement il faut Berkeley DB (pour avoir “db_185.h”)

à vérifier pourquoi on a besoin d’un tel système de base de données pour compiler le kernel Linux :wink:
intuitivement ce n’est que le driver en question (aic7xxx) qui en a besoin
mais je ne suis pas très sûr

l’erreur s’est produite X fois: est-ce que les X fois c’était avec le “driver” aic7xxx? si oui, c’est curieux, faudrait regarder si randconfig a vraiment été appelé correctement (cela ne sonne pas très random)... si non, cela veut dire que aicdb.h est créé autre part dans le kernel, et pas que pour aic7xxx

**Comment by Heartbroken-Git** [comment]
Effectivement si c'est généré par le build en lui même c'est surprenant qu'il ne le trouve pas.
La vérification dans le randconfig c'est du ressort de @Aexelion donc je lui assigne la tâche mais il faudrait effectivement voir si ça vient toujours du même driver :/

**Comment by FAMILIAR-project** [comment]
Non ce n'est pas si surprenant: le build (pour générer le fameux "aicdb.h") s'appuie sur un autre header ("db_185.h") qui doit être présent sur la machine à condition d'installer Berkeley DB. 
cf https://github.com/torvalds/linux/blob/master/drivers/scsi/aic7xxx/aicasm/Makefile#L45-L58

**Comment by Heartbroken-Git** [comment]
Ah ok, ça commence à avoir du sens maintenant oui

**Comment by micleb** [comment]
Je vais travailler là dessus avec @Aexelion  aujourd'hui.
Il faut que je lui demande comment on génère un .config à partir du KCONFIG_SEED pour reproduire l'erreur.

**Comment by Aexelion** [comment]
En principe le randconfig fait bien du random après pour ré-obtenir le même .config que durant la configuration qui à rater (ou que tu veux re-tester une config que tu as eu) tu fait la commande : 
KCONFIG_SEED=0xE4B204B make randconfig
Il faut juste connaitre le seed (donné en début de compilation avec randconfig).

**Comment by micleb** [comment]
Petit récap : j'ai re-généré un .config à partir du KCONFIG_SEED mais la compilation se déroule normalement ô.O
Je ne sais pas pourquoi, j'ai désinstallé tous les paquets qui avaient été installés par des compilations précédentes et pourtant le programme ne plante pas à cause de l'absence de aicdb.h

Faut faire d'autres tests, et la prochaine fois que ça plante uploader le .config au lieu du seed ;-)

**Comment by FAMILIAR-project** [comment]
> et la prochaine fois que ça plante uploader le .config au lieu du seed ;-)

OUI! 

btw il serait peut-être intéressant de pouvoir lancer tuxml sur un .config particulier... pour notamment permettre de répliquer une compilation, voire de comparer certaines métriques (eg taille du kernel, temps de boot) selon la machine utilisée

**Comment by micleb** [comment]
Ca y est je suis retombé sur le bug ! 🥇 
Et j'ai pu récupérer l'output de tuxml, le .config, les fichiers std.logs et err.logs !

* output de tuxml : https://pastebin.com/raw/EySKCVR2
* le .config : https://pastebin.com/raw/YyS45af0
* std.logs : https://pastebin.com/raw/WXZJ7LYC
* err.logs : https://pastebin.com/raw/7CVvJihU

Je viens de remarquer une chose, **le .config que je viens d'utiliser est une version 32 bits et le KCONFIG_SEED de l'issue génère lui aussi un .config en 32 bits, et ma machine est en 64bits...**

**Comment by Heartbroken-Git** [comment]
Le problème pour le 32 bits n'en était pas un en fait. La limitation de 64 bits n'était pas encore en place quand le seed avait été généré.
