### ISSUE TITLE
TPDIM.py (Docker)

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#30]
Dans Dockerfile 
FROM tuxml/debiantuxml:latest

alors que l'image s'appelle tuxml/tuxmldebian !? 

Pas de spécification sur les packages à installer comme python3 ou mysql... 
Bref TPDIM.py et Dockerfile me semblent incomplets.

**Comment by FAMILIAR-project** [comment]
OK je viens de comprendre... 
Il y a deux images:
https://hub.docker.com/u/tuxml/ 

`FROM tuxml/debiantuxml:latest` est l'image de base sur laquelle s'appuie tuxmldebian
problème: on ne sait pas du tout ce que contient cette image (ie c'est quoi le Docker file de debiantuxml? @CaptainMexiko: tu pourrais nous en dire plus?). 

Je pense que c'est une mauvaise pratique d'avoir 2 images Docker. 
Il faut utiliser une image de base connue (basée sur Debian) et maintenir une seule image Docker (tuxmldebian).

Cette issue est reliée: 
https://github.com/TuxML/ProjetIrma/issues/13 

En s'appuyant sur les retours de @CaptainMexiko je pense qu'on peut très rapidement corriger le problème en créant un Docker file correct

**Comment by ghost** [comment]
Alors au début il n'y avait qu'une seule image, mais vu qu'à chaque fois que l'on buildait l'image (après chaque changement de tuxml.py ou mlfood.py) on devait ajouter le kernel linux en entier, pareil pour le push, et c'est très long  (avec la connexion internet de la fac c'était pas loin d'une heure ). Donc j'ai  décidé d'utiliser une image intermédiaire que l'on build que une fois ,  qui contient le kernel linux, et certaines dépendances de base.

**Comment by micleb** [comment]
Et au lieu de rebuild l'image en mettant les fichiers tuxml à chaque fois (après chaque commit), est-ce qu'on pourrait utiliser l'image intermédiaire qui contient les dépendances ?

Puis via mlfood ou un autre script on exécute un **git clone repo_tuxml** avant d'exécuter tuxml.py.
Ca éviterait de casser l'image à chaque fois, de la reDL etc

**Comment by ghost** [comment]
Ben normalement l'image intermédiaire n'est jamais cassé, car personne n'y touche à part moi. Sinon non car on veut que l'utilisateur lambda n'est que besoin de MLfood.py sur son pc. Sinon autant git clone de base.

**Comment by FAMILIAR-project** [comment]
@CaptainMexiko ton explication a du sens, je comprends mieux! 
tu aurais quelque part le Dockerfile de l'image intermédiaire? (ou comment tu l'as construite)

**Comment by ghost** [comment]
Oui, je vais le rajouter sur le github.

**Comment by micleb** [comment]
@CaptainMexiko non ça ne revient pas à "git clone de base", car l'utilisateur lambda tourne sur une ubuntu, une arch ou même une debian où les dépendances ne sont pas installées.
Alors que l'image intermédiaire contient tous les paquets nécessaires à la compilation

Actuellement ça se passe comme ça : 
* quelqu'un fait un commit
* il exécute tpdim pour mettre à jour l'image = image intermédiaire + nouveau fichier tuxml (risque de casser l'image)
* exécute mlfood
* mlfood télécharge la dernière image
* lancement de tuxml

Moi ce que je propose c'est : 
* quelqu'un fait un commit
* il exécute mlfood
* mlfood télécharge l'image intermédiaire (qui n'est que très rarement modifiée)
* mlfood lance les dockers
* il clone notre repo github depuis les dockers
* il lance tuxml

Donc il y a beaucoup moins de risques de casser l'image

**Comment by ghost** [comment]
Faudrait essayer,  mais pour moi l'image intermédiaire va être long à dl.

**Comment by micleb** [comment]
Pourquoi elle est plus longue à DL ?

**Comment by ghost** [comment]
C'est une supposition, mais su clean toutes tes images docker, tente un docker system prune puis MLfood

**Comment by FAMILIAR-project** [comment]
Il nous faut absolument un script pour fabriquer l'image intermédiaire. Pour la faire évoluer, pour reproduire l'image et pour éviter la situation d'aujourd'hui. 

Il est clair qu'on ne reconstruira l'image intermédiaire que si vraiment nécessaire

**Comment by ghost** [comment]
Justement, je veux modifier TPDIM (voir en faire un vrai programme ) pour pouvoir faire ce genre de choses sans avoir à  connaître les commandes docker, et pouvoir générer automatiquement des dockerfile, push sur le repository de son choix,  build les images en ayant juste à mettre le nom de l'image

**Comment by FAMILIAR-project** [comment]
vmacher:baseImg macher1$ docker run -it tuxml/debiantuxml
root@0a2353ddf1bb:/# python3 --version
Python 3.5.3
root@0a2353ddf1bb:/# exit
exit
vmacher:baseImg macher1$ docker run -it tuxml/tuxmldebian:latest
root@6977ea59b0ea:/# python3 --version
bash: python3: command not found
root@6977ea59b0ea:/# 

Comme si l'image de base (intermédiaire) n'avait pas été pris en compte...

**Comment by FAMILIAR-project** [comment]
bash: less: command not found
sur l'image tuxmldebian

par contre il y a bien le dossier TuxML avec les sources du kernel

**Comment by FAMILIAR-project** [comment]
J'ai réussi à créer une image correcte simplement avec la commande: 
`docker build -t tuxml/tuxmldebian .`

(cette commande est d'ailleurs utilisée dans TPIDM.py) 

Et on a bien accès à python3:
```
Successfully built 834f65cc51ff
Successfully tagged tuxml/tuxmldebian:latest
vmacher:ProjetIrma macher1$ docker run -it tuxml/tuxmldebian
root@b87ef7a18e41:/# python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
```

(à noter que `docker run -it tuxml/tuxmldebian:latest` ne fonctionnerait pas, car il utiliserait l'image du Hub) 

J'ai lancé une compilation à la main (`docker run -it tuxml/tuxmldebian /TuxML/tuxLogs.py | tee Logs/2988/output.logs`) et cela a l'air de marcher.

Conclusion: je ne sais pas comment tuxml/tuxmldebian a été build/push, mais il n'y a pas de raison que cela ne fonctionne pas, même avec l'image de base actuelle

**Comment by FAMILIAR-project** [comment]
Objectif général: faciliter la création d'une image Docker par tout un chacun (c'est trop laborieux et dépendant d'un super héros actuellement: il faut un script...) 

(cf aussi https://github.com/TuxML/ProjetIrma/issues/27)

**Comment by alemasle** [comment]
Nous nous sommes mis d'accord sur un système d'image avec tags, une image "prod" correspondant à l'image fonctionnelle ( master ) ainsi qu'une image "dev" correspondant à l'image en cours de développement. @CaptainMexiko est en ce moment dans le développement du Manager d'Image TPDIM.py afin de les gérer et les manipuler.
