### ISSUE TITLE
Mesure du temps de compilation 

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#31]
Je n'ai pas la solution à ce problème, mais je partage le problème... 

Quand on compile une configuration, il est probable que tuxml aille chercher des packages manquants. 
Il y a donc un "biais": certaines configurations prendront énormément de temps à cause des packages manquants, pas à cause de la compilation proprement dite. 

Sur certaines machines, les packages nécessaires pour compiler la configuration sont peut-être déjà installés. Difficile de comparer donc! 

solution possible: 
 * pré-installer un maximum de packages
 * soustraire le temps d'installation des packages 
 * répliquer la compilation une fois qu'on a installé tous les packages

**Comment by micleb** [comment]
Cette issue est en lien avec la #32, j'ai d'ailleurs déjà un peu répondu à certains des problèmes

Je pense que ce ne vaut pas le coût de comparer les temps de compilation, dans tous les cas on dépendra du hardware : CPU, RAM, HDD/SSD. Donc quelque soit la mesure qu'on met en place, les comparaisons seront toujours faussées.
Actuellement, dans la BDD, il y a des compilations qui ont été faites sur les dockers de l'ISTIC, sur des laptop, sur des ordis fixes, sur des serveurs. Donc des configurations déjà très hétérogènes.

> pré-installer un maximum de packages

Pourquoi pas... Il faudrait ajouter le plus de paquets aux dépendances minimales.
Mais ça implique de sauvegarder les paquets qu'on installe pendant une compilation pour ne pas les perdre.

> soustraire le temps d'installation des packages

J'ai fait quelques tests et lorsque la compilation plante à cause d'un fichier/paquet manquant, le programme met entre 30 et 60 secondes pour trouver la dépendance et l'installer.
Je trouve que c'est relativement négligeable par rapport à la durée totale de la compilation. Mais cette mesure reste facile à mettre en place.

> répliquer la compilation une fois qu'on a installé tous les packages

Cette idée là me paraît un peu *overkill* ! Une compilation est déjà longue de base, si on la fait deux fois de suite on n'a pas fini !

Faut voir ce que le reste de l'équipe en pense.
Je serais d'avis d'utiliser la compilation incrémentale (#32) pour faire un maximum de compilations en un minimum de temps.
Comme ça on pourra lancer les tests sur les noyaux et trouver des corrélations plus rapidement.

**Comment by BzhErlb** [comment]
**Pour le temps d'installation des packages :** 

Dans le code de Mickaël il y a une boucle où ça compile et recommence si paquets manquants jusqu’à que ça fonctionne.
Comme le temps de début est stocké avant la boucle ça compte effectivement le temps d'installation des paquets manquants.

Pour Mickaël : Est-ce qu'il ne suffirait pas de déplacer "start_time = time.time()" de tuxml.py de la ligne 236 à la ligne 242, juste avant l'appel à if (compilation() == - 1)  :  pour ne pas compter le temps des compilations ratées?

A mon avis ce n'est pas plus compliqué que ça.

> Je pense que ce ne vaut pas le coût de comparer les temps de compilation, dans tous les cas on dépendra du hardware : CPU, RAM, HDD/SSD. Donc quelque soit la mesure qu'on met en place, les comparaisons seront toujours faussées.

Pour faire des comparaisons, une idée peut être compliquée à bien implémenter mais qui pourrait marcher serait de regrouper les machines  en groupe de puissance un peu près équivalente et de comparer les mesures qu'entre machines de même groupe, quitte à trouver un moyen de "normaliser" ça pour pouvoir tout comparer. 

Mais il faut être capable de définir quels critères (le moins possible idéalement) pour dire que 2 configurations sont suffisamment proches pour faire des comparaisons pas trop faussées. Il n'y a pas tant de critères que ça, c'est avant tout le CPU qui influe, à priori suivit du ssd, puis de la RAM.  

Ce n'est pas forcément inintéressant de réfléchir au problème car il va revenir pendant la phase de machine learning si l'on veut établir des corrélations entre temps de boot et options.

**Comment by micleb** [comment]
Après discussion avec l'équipe, je vais soustraire le temps d'installation des paquets au temps de compilation

WIP
