### ISSUE TITLE
Compilation and Cores

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#33]
Bonjour, 

Nous avons eu quelques soucis et effectué quelques itérations sur la spécification du nombre de coeurs. 
Je pense que le problème de la gestion des paramètres a été correctement réglé. 

Cependant, malgré le fait de spécifier un nombre de coeurs élevés, les temps de compilation ont largement augmenté, sans raison particulière. 

J'ai un peu expérimenté et j'ai l'impression que l'erreur venait du fait qu'il faut utiliser quelque chose comme:
`make -C path -j8` 
et non 
`make -C path -j "8"` ou `make -C path -j 8`
(il faut coller le paramètre à -j, sans espace)

J'ai hardcodé la valeur 8 actuellement dans tuxml.py, et j'obtiens de nouveau les temps de compilation que j'avais précédemment. 
J'ai mis à jour l'image Docker également. 

Il faudrait valider mon hypothèse sur la façon de compiler et prendre réellement en compte l'argument sur le nombre de coeurs.

**Comment by micleb** [comment]
Bonjour, effectivement il faut que le '-j' et le chiffre soient collés.

https://wiki.gentoo.org/wiki/Kernel/Configuration#Build
> For processors with multiple cores, make all the cores do the work. Add the option `-j(<NUMBER_OF_CORES> + 1)`.

http://www.tuxradar.com/content/how-compile-linux-kernel
> Note: on a multi-core machine you can run `make -j4 all` for the first command to run multiple compilation processes at the same time.

http://www.linux-databook.info/?page_id=2319
> The book, Linux Kernel in a Nutshell, discusses the use of the -j option when compiling the kernel to specify the number of threads to use during the compile. **It recommends using -jX where X, the number of threads, is set to twice the number of CPUs available.** If -j is not specified, the default is for a single thread to be used. **I have found that the recommendation of 2x the number of CPUs is too high. My own experiments show that X should be, at most, equal to the number of CPUs.**

C'est étonnant ça, car sur mon serveur il y avait une réelle différence de temps quand j'utilisais `-j` même avec un espace.

Je vais voir avec Erwan, car il a réussi à récupérer le nombre de coeurs sur la machine. Donc il faudrait utiliser cette information quand je lance `make -j(<nb_coeurs_trouvés_par_erwan> + 1)`, et laisser tomber l'option `--cores`

P.S : Dans l'immédiat je vais garder `--cores`, je vais juste coller le '-j' et le chiffre.

**Comment by micleb** [comment]
Ca y est j'ai push les modifications
`subprocess.call(["make", "-C", tset.PATH, "-j" + str(tset.NB_CORES)], stdout=std_logs, stderr=err_logs)`
Il faudrait reconstruire l'image, je laisse quelqu'un de la team docker (@alemasle @CaptainMexiko) s'en occuper ;-)

**Comment by micleb** [comment]
Je viens de push une nouvelle version, utilisant cette fois-ci tous les coeurs de la machine par défaut.
Si le paramètre "--cores" est utilisé, on utilise la valeur fournit par l'utilisateur, sinon on récupère le nombre de coeurs grâce à **get_hardware_details()**.

```
if args.cores:
        tset.NB_CORES = args.cores
    else:
        try:
            tset.NB_CORES = int(tenv.get_hardware_details()["cpu_cores"])
        except ValueError:
            tcom.pprint(1, "Wrong number of CPU cores value")
            sys.exit(-1)
```

Exemple d'affichage
`sudo ./core/tuxml.py linux-4.13.13/ -v`
```
[*] 2017-12-19 11:23:23 | Cleaning previous compilation
[*] 2017-12-19 11:23:42 | Randomising new config file
[*] 2017-12-19 11:23:49 | Getting environment details
{'distrib_version': '9.1', 'os': 'Linux', 'distribution': 'debian', 'kernel': '4.9.0-3-amd64'}
{'arch': 'x86_64', 'ram': '8178832', 'cpu_freq': '1999', 'cpu': 'Intel(R) Xeon(R) CPU           E5405  @ 2.00GHz', 'cpu_cores': 8}
{'tuxml_version': 'pre-alpha v0.2', 'core_used': 8, 'libc_version': '2.24-11+deb9u1)', 'gcc_version': '6.3.0-18)'}
[*] 2017-12-19 11:23:49 | Finding package manager
...
```
On voit bien que le processeur dispose de 8 coeurs (2ème ligne) et que le nombre de coeurs utilisés est identique (3ème ligne)
