### ISSUE TITLE
L'horodatage des dossiers sous Logs/ n'est pas bon

### ISSUE THREAD

**Issue by micleb** [TuxML/ProjetIrma#35]
Salut, je viens de remarquer que les dossiers de Logs n'étaient pas au bon format.
Normalement il devrait être nommés de cette manière : JJMMAAAA_HHMMSS mais ce n'est pas le cas.

> micleb@kcs:~/Documents/ProjetIrma$ ls Logs/
19122017_173524  19122017_175133  19122017_18293  19122017_1849  19122017_18934

Je ne sais pas pourquoi mais les '0' des heures, minutes ou secondes ne passent pas.

Donc ce n'est pas évident pour faire le tri derrière. Par exemple : 19122017_1849, est-ce que c'est 18:49:00 ou 18:00:49 ?

Est-ce que tu pourrais corriger ça @alemasle ?

Merci ;-)

**Comment by alemasle** [comment]
Je me demande si ça ne dépend pas du système, parce que de mon coté les '0' sont bien affichés pour les dossiers, surtout que c'est toi qui avait modifié ma création de nom de dossier avec "time" pour que ça corresponde à ce que tu voulais et régler justement ce problème de "0".
De mon côté les 0 sont bien la

**Comment by micleb** [comment]
Bah oui, je me souviens bien de ça. C'est pourquoi ça m'étonne d'avoir ce genre de nom de dossier.
Et pourtant je suis passé par MLfood, tuxlog etc

EDIT : My bad, ma version de mlfood n'était pas à jour :-/
