### ISSUE TITLE
Compilation errors/warnings/output in the database

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#38]
Bonjour,

Je ne sais pas si c'est déjà le cas, mais pour chaque configuration/compilation il faudrait avoir:
 * les erreurs de gcc (s'il y en a)
 * les warnings de gcc (s'il y en a)
 * l'output de gcc 
dans la base de données...

Les warnings par exemple cela m'intéressent particulièrement.

**Comment by Heartbroken-Git** [comment]
Possible doublon avec #24 . A voir physiquement si on parle de la même chose.
