### ISSUE TITLE
Obtention des logs 

### ISSUE THREAD

**Issue by Heartbroken-Git** [TuxML/ProjetIrma#4]
Il serait intéressant d'avoir un paramètre à donner à `mlfood.py` qui permettrait de récupérer tous les logs que le programme va rencontrer durant son fonctionnement. Il peuvent être donnés sous la forme d'un unique fichier mais le top du top serait d'avoir plusieurs fichiers de logs décrivant chacun leurs étapes.

Idée originale de @micleb.

**Comment by alemasle** [comment]
La commande `MLfood.py` ajoute maintenant les logs err.logs, std.logs et tuxml.logs dans le Dossier Logs/ présent dans le dossier courant de `MLfood.py`.
err.logs et std.logs sont les logs créés par le script `tuxml.py` et le log tuxml.logs est l'output complet + stacktrace d'erreur de l'execution du script  `tuxml.py`
