### ISSUE TITLE
Pre-configuration du kernel Linux

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#40]
Bonjour, 

Un "sampling" (échantillonnage) aléatoire est une première solution intéressante pour explorer l'espace de configurations. Nous utilisons jusque là make randconfig et a priori cela convient à nos besoins [1]

Il est parfois nécessaire d'avoir plus de maîtrise sur la façon de choisir des configurations. 
Pourquoi? 
 * on veut un "échantillonnage" dans lequel on insiste davantage sur certaines options (ou on écarte de facto certaines options) pour mieux comprendre l'influence de certaines options... typiquement on va faire de l'apprentissage itératif, qui nécessite de recentrer l'échantillonnage sur certaines zones de l'espace de configuration  
 * on veut écarter certaines options qui ne sont pas ou difficilement supportés par nos machines de test (exemple: CONFIG_32BIT) 
 * on veut écarter certaines options qui sont jugées peu "intéressantes" ou au contraire forcer certaines options (comme CONFIG_DEBUG_INFO car on souhaite vérifier que cette option augmente effectivement la taille du kernel)

Deux solutions sont envisageables:
 * comme avec CONFIG_64BIT, on peut apparemment forcer les valeurs de certaines options dans un .config pré-établie et ensuite appeler make randconfig... vérifier que c'est bien le cas 
 * utiliser les "poids" de make randconfig: je suis moins "fan" car le mécanisme me semble très spécifique et peu documenté, je ne sais pas si on peut avoir confiance  

Une fois qu'on est capable d'effectivement de "pré-configurer" le kernel Linux, il faudrait intégrer ce mécanisme dans la commande Tuxml. 
**L'idée est de pouvoir facilement lancer des campagnes de compilation avec certaines pré-configurations.**   

[1] modulo qu'il faudrait vérifier que randconfig est bien "random", mais je laisse de ce côté cet aspect là dans cette issue... Il y a une issue dédiée: https://github.com/TuxML/ProjetIrma/issues/10

**Comment by FAMILIAR-project** [comment]
Une autre issue qui est reliée à cette thématique c'est l'idée d'avoir une compilation incrémentale https://github.com/TuxML/ProjetIrma/issues/32
(intuitivement on ne va changer que certaines options pour ne pas avoir à recommencer toute la compilation)

**Comment by Heartbroken-Git** [comment]
Exploratoire, pas immédiatement nécessaire au passage à l'échelle ou au rendu final. Je retire donc l'issue du projet pour les grilles.

**Comment by alemasle** [comment]
On utilise le fichier tuxml.config pour mettre des options que nous pré-définissons à l'avance. Voir #98
