### ISSUE TITLE
Manière de compiler le kernel Linux (gcc)

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#41]
Bonjour, 

Nous utilisons make et la palanquée de Makefile pour compiler le kernel Linux. 
En interne c'est gcc qui est utilisée, et ce compilateur a lui-même des centaines d'options. 

Comme cela a été discuté à la soutenance on peut se poser les questions suivantes:
 * quel est le jeu de paramètres de gcc utilisé par défaut? 
 * peut-on facilement changer le jeu de paramètres? (il serait par exemple intéressant de voir comment on peut réduire la taille du kernel avec -Os http://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html) 

Idéalement, il serait intéressant d'avoir des "profils" pré-établis de paramètres associé à gcc, et qu'on puisse activer ces profils dans Tuxml. 
** L'idée est de pouvoir lancer des campagnes de compilations avec des options de gcc bien spécifiques **

**Comment by Heartbroken-Git** [comment]
J'ajoute @Aexelion qui s'était intéressé au Makefile pour le `make random`. Il devrait pouvoir aider @micleb.

**Comment by ghost** [comment]
Je viens de voir dans le `Makefile` et dans les options possibles qu'il existe `CC_OPTIMIZE_FOR_PERFORMANCE`, `CC_OPTIMIZE_FOR_SIZE`, et `OPTIMIZE_INLINING` qui peuvent être présentes dans le `.config.

`CC_OPTIMIZE_FOR_SIZE` active `-Oz` et `-Os`, il n'est pas mis par défaut
`CC_OPTIMIZE_FOR_PERFORMANCE` active `-O2`, il est mis par défaut
`CC_OPTIMIZE_INLINING` force l'inlining des fonctions au lieu de laisser gcc décider. Cela peut baisser la taille du kernel mais aussi dégrader les performances.
D'expérience `-O3` est trop agressif et optimize "trop", ce qui peut changer le comportement de l'application.

**Comment by Aexelion** [comment]
Je viens de voir qu'il est possible d'afficher les commandes qui serait effectuées (sans les exécuter) par le `make`, en utilisant la commande `make -n`. Je vais tester ça et vérifier le lien entre les options du `.config` données par @PLeLuron et les options actives pour `gcc`

**Comment by Aexelion** [comment]
De ce que j'en ai vu, `gcc -O2` est utilisé pour l'option `CC_OPTIMIZE_FOR_SIZE` mais beaucoup moins que pour `CC_OPTIMIZE_FOR_PERFORMANCE`. De même que `gcc -Os` est utilisé dans les 2 cas également. Je continuerais de vérifier pour donner de plus amples détails.

**Comment by acherm** [comment]
Intéressant, j'avais loupé cette passionnante "issue" 
@micleb possible de logger les options de gcc *réellement* utilisés lors de la compilation? (avec make -n)

**Comment by alemasle** [comment]
Pour les options de GCC on n'y touche pas directement. Pour ce qui est de la taille, nous avons la possibilité de créer des .configs ayant les options de tinyconfig pré-intégrée dedans dans l'espoir de compiler plus vite des noyaux plus petit. Les options de tinyconfig comprennent:

```
# CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE is not set
CONFIG_CC_OPTIMIZE_FOR_SIZE=y
```

Nous pouvons obliger l'utilisation des options de tinyconfig.
