### ISSUE TITLE
QEMU? 

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#43]
Une fois compilée, il est intéressant de faire quelque chose avec le kernel: 
 * est-ce que cela boot? 
 * combien de temps cela prend pour booter? 
 * utiliser la commande 'perf' pour tester certaines propriétés du kernel 

QEMU semble être une solution prometteuse, mais encore rien de vraiment concret en l'état

**Comment by Heartbroken-Git** [comment]
Alors pour rappel de ce que j'avais mis sur Slack, j'en était à pouvoir récupérer l'output écran de Linux lors de son *boot*. Ainsi on avait un fichier texte à *parser* à la recherche de "kernel panic" ou équivalent ou de l'écran de login si le noyau boot. Après coup si l'expérimentation fonctionne on pourra l'intégrer aux scripts tuxml déjà existant et utiliser les fonctions de chrono déjà utilisée pour la compilation avant le boot puis à la lecture de l'écran de login pour obtenir le temps de boot.

Enfin en ce qui concerne 'perf' je ne connais pas encore cette commande mais je m'y intéresserais 😄

**Comment by FAMILIAR-project** [comment]
Pour perf: https://perf.wiki.kernel.org/index.php/Main_Page (on pourrait mesurer des tas de choses sur le kernel... btw est-ce qu'auto test utilise perf?) 

mais la priorité haute est d'automatiser la vérification du "boot" avec QEMU!

**Comment by Heartbroken-Git** [comment]
Les premiers tests de mon script python ont l'air concluant, je pense pouvoir tester si cela boot ou non. Je vais push le script en l'état sur la branche `bootChecker_addition`.
Par contre @CaptainMexiko, il faudra ajouter qemu aux VMs pour qu'il marche. ~~Et il faudrait mettre une image debian x86_64 compatible QEMU (.qcow2) aussi quelque part dans le projet.~~

**Comment by Heartbroken-Git** [comment]
Note pour @CaptainMexiko, comme indiqué mercredi dernier il ne sera plus nécessaire de mettre une image debian dans le Docker par contre il faut bien `qemu`. De plus comme rappelé sur le Slack il faudrait que tu vérifies que la commande `mkinitramfs` est bien de base dans la distro debian de l'image Docker et dans le cas contraire il faudrait que tu l'ajoutes.

**Comment by Heartbroken-Git** [comment]
L'intégration de QEMU au projet afin de tester le boot des noyaux compilés progresse bien.
Cf la PR #50 pour l'ajout au projet de cette nouvelle fonctionnalité. Je fermerai l'issue lors du merge de celle-ci.

**Comment by Heartbroken-Git** [comment]
Petit problème que je viens de découvrir en faisant des tests dans le train. La commande `perf` n'est pas inclus dans le kernel linux. Il faudrait l'installer ce qui rend la tâche bien plus ardue :/

**Comment by Heartbroken-Git** [comment]
Je remets ici la roadmap perso quand à l'évolution du système de `initramfs` : 
- V0 : Mise en place d'un initramfs construit au préalable de façon arbitraire en amont sur le Docker et modification du script de test de boot pour qu'il fonctionne
- V1 : Modification du script pour qu'il envoie le temps de boot aussi
- V2 : Mise en place d'un script sh pour générer le initramfs 
La V0 est presque finie, juste à ce que @CaptainMexiko ajoute le `initramfs` arbitraire au Docker et à tester. Elle est sur la branche `v0-newInitramfs` mais le développement est sur pause afin de se concentrer sur la PR #58
