### ISSUE TITLE
Choix de LICENCE

### ISSUE THREAD

**Issue by Heartbroken-Git** [TuxML/ProjetIrma#47]
LE fait de devoir éventuellement mettre une image de debian dans le repo git devrait nous amener à nous poser la question quand à la licence d'utilisation que l'on veut mettre sur le repo. En effet je ne pense pas qu'il est possible de mettre l'image de debian sur un repo qui n'est pas open-source (à vérifier). Quand bien même, si à terme on veut pouvoir être aidé de et aider la communauté Linux il faut forcément passer en libre et donc avoir une licence compatible.

Personnellement j'ai un peu l'habitude de ces questions là donc si vous n'avez pas d'idées pas d'envie particulière pour la licence je peux m'en charge complètement.
Pour ceux que ça intrigue j'utilise énormément la WTFPL2.0 ou la LPRAB1.0 (la version française de la WTFPL2.0) mais vu l'impact du projet et surtout le fait qu'il joue avec des VM et des noyaux une clause de dégagement de responsabilité et de non-garantie me paraît essentielle. Ainsi la MIT License me paraît être le strict minimum.

**Comment by ghost** [comment]
Choix effectué, on prend la licence Apache 2.0
