### ISSUE TITLE
Ajout de la date et l'heure avant chaque ligne de log

### ISSUE THREAD

**Issue by Heartbroken-Git** [TuxML/ProjetIrma#5]
Lors de l'utilisation de `tuxml.py` en mode *debug* cela peut être une bonne idée d'ajouter la date et l'heure avant chaque ligne de logs. Ainsi on pourrait plus facilement diagnostiquer certains problèmes d'exécution particulièrement longues.

Idée originale de @micleb.

**Comment by micleb** [comment]
Fait, ce sera dispo dans la prochaine maj
