### ISSUE TITLE
Générer une doc automatique (HTML/PDF)

### ISSUE THREAD

**Issue by micleb** [TuxML/ProjetIrma#51]
Il existe des outils automatique pour générer la doc au format HTML et PDF (style JavaDoc)

@Heartbroken-Git m'a rapidement briefé sur [Doxygen](http://www.stack.nl/~dimitri/doxygen/)

Par contre il faudrait reformater toute la documentation qu'on a fait actuellement, étant donné que celle-ci ne respecte pas les standards Doxygen.

Peut être qu'il existe aussi d'autres outils plus adaptés pour Python...

À investiguer...

**Comment by Heartbroken-Git** [comment]
Après discussion et mise au point il apparaît assez important pour la partie "reprise de code" du rendu de commencer dors et déjà à travailler sur de la documentation. Il semblerait que l'on parte sur une documentation automatique assistée par Doxygen.

**Comment by micleb** [comment]
J'ai regardé comment fonctionnait doxygen sous python.

J'ai déjà commencé à commenter le code du module core (cf branche doxygen-addition).
Pour commenter vos fichiers vous devez utiliser : 
* en guise d'entête de fichier : 
```
## @file mon_fichier.py
#  @author NOM Prénom
#  @author NOM2 Prénom2
# [...]
#  @copyright Apache License 2.0
#  @brief Explication breve de ce que fait le fichier, à quoi il sert etc 
#  @details Explication détaillée
```

* avant chaque fonction : 
```
## @author  NOM Prénom
#  @author NOM2 Prénom2
#  [...]
#
#  @brief   Explication breve de la fonction
#  @details Explication détaillée
#
#  @param   param1 explication
#  @param   param2 explication
#  [...]
#
#  @returns value1 explication
#  @returns value2 explication
#  [...]
```
C'est plutôt proche de la javadoc, vous pouvez aussi rajouter des `@warning`, `@todo` etc

Ensuite pour générer la doc au format HTML et LaTex : `doxygen tuxml_doxyfile`

**Comment by alemasle** [comment]
Utilisation de Doxygen faite.
