### ISSUE TITLE
IrmaDB-master est gros

### ISSUE THREAD

**Issue by ghost** [TuxML/ProjetIrma#52]
Accumuler les fichiers de log en base64 dans la nouvelle BDD fait qu'on atteint une taille de BDD assez gigantesque.

La version dev de TuxML convertit les fichiers .config et de log en base64 avant de les envoyer à la bdd. Un problème : un .config de 100k caractères, une fois encodé en base64 fait 145k caractères. Vous pouvez tester chez vous [ici](https://www.base64encode.org/) et faire wc -c pour compter le nombre de caractères.

On peut aussi voir que les champs "stdlog_file" et "errlog_file" peuvent facilement atteindre 500ko.

Un petit coup de gzip ou de bzip2 ne serait pas de refus, et ils sont dans la lib standard de python.

**Comment by micleb** [comment]
Ca a été fait dans le commit 4fbc271b843825e1b7c3cb5f30edb7f5de5345cf

J'utilise l'algo de compression bzip2 (**import bz2** en python)

Les champs config_file, stdlog_file et errlog_file sont désormais des **LONGBLOB** au lieu de **LONGTEXT**
