### ISSUE TITLE
MLfood incrémentale

### ISSUE THREAD

**Issue by micleb** [TuxML/ProjetIrma#57]
Actuellement on ne peut pas utiliser MLfood avec le mode incrémentale de tuxml.
Si on lance `./mlfood.py 10` il va lancer 10 tuxml dans 10 conteneurs docker différents. On ne peut donc pas réutiliser les fichiers des précédentes compilations.

Il faudrait rajouter une autre option à mlfood pour spécifier le nombre de tuxml à lancer dans chaque docker.
Par exemple : `./mlfood.py 10 5` lancera 5 tuxml dans chacun des 10 conteneurs docker.

**Comment by alemasle** [comment]
WIP

**Comment by alemasle** [comment]
Comme on en a parlé, j'ai rajouté l'option incrémental à MLfood.py il suffit de rajouter un nombre entier de plus en paramètre ( Ex: ./MLfood.py 10 5 ) lancera 5 compilation en mode incrémental sur chacun des 10 dockers créés. Si ce paramètre n'est pas précisé alors il sera par défaut à 1 et le fonctionne sera le même que précédemment.

**Comment by alemasle** [comment]
Le paramètre incrémental sera transféré à tuxML par le biais de "--incremental <incr>"
