### ISSUE TITLE
Utiliser autre chose que JHipster

### ISSUE THREAD

**Issue by ghost** [TuxML/ProjetIrma#6]
Quelques problèmes avec JHipster, par rapport à une base de données SQL classique:

* Les types dans la base de données sont basés sur des classes java, comme `java.time.Instant`ou `java.time.LocalDateTime` qui sont notre seul moyen d'avoir des heures et minutes dans la base de données. Aucune doc ne précise comment utiliser ces types sans java.

* L'api HTTP est trop limitée pour ce qu'on veut faire: les données demandent un formatage rigoureux et on a juste GET POST et DELETE, sans pouvoir choisir les champs. Le corps des requêtes doit être formaté en JSON et cela peut mener à des trucs très moches (blob en base64 pour n'en citer qu'un)

* Erreurs très peu précises quand les requêtes échouent. Une stack trace java et uniquement un "could not prepare statement" peuvent se montrer très frustrants quand on debug.

* A voir avec @CaptainMexiko mais c'est pas très simple d'ajouter des colonnes dans la bdd.

Proposition de solution:
* Utiliser autre chose. PostgreSQL, SQLite, MySQL, peu importe.

Bonus: Une jolie erreur que j'essaie de régler sans succès:
`could not prepare statement; SQL [select irma_db0_.id as id1_0_, irma_db0_.boot as boot2_0_, irma_db0_.boottime as boottime3_0_, irma_db0_.compilationtime as compilat4_0_, irma_db0_.jhi_compile as jhi_comp5_0_, irma_db0_.configfile as configfi6_0_, irma_db0_.configfile_content_type as configfi7_0_, irma_db0_.coresize as coresize8_0_, irma_db0_.jhi_date as jhi_date9_0_, irma_db0_.dependance as dependa10_0_, irma_db0_.dependance_content_type as dependa11_0_, irma_db0_.erreur as erreur12_0_, irma_db0_.erreur_content_type as erreur_13_0_ from irma_db irma_db0_ limit ?]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement`

**Comment by ghost** [comment]
La page de test d'API de JHipster renvoie aussi des erreurs 500 sur les requêtes qui sont censées être des exemples valides.

**Comment by Heartbroken-Git** [comment]
@CaptainMexiko et @micleb sont dessus et vont mettre en place un LAMP plutôt que *JHipster*. On fermera cette *issue* à l'issue (lol)

**Comment by Heartbroken-Git** [comment]
@CaptainMexiko, @PLeLuron et @micleb on mis en place une BdD de remplacement. Les contacter pour plus de détails mais problème résolu.
