### ISSUE TITLE
MLfood et base de données 

### ISSUE THREAD

**Issue by acherm** [TuxML/ProjetIrma#60]
MLfood.py semble envoyer les données à IrmaDB. 
Je ne sais pas si c'est "normal" mais clairement il n'envoie pas les logs par exemple. 

Pas trop sûr de l'utilité de "Properties": à quoi ça sert? (Arch et Version à la rigueur OK, même si ce n'est pas utilisé a priori) 

Impression que la "vraie" base de données est IrmaDB_prod, mais elle n'est pas encore utilisée par MLfood.

**Comment by ghost** [comment]
Properties, Arch et Version servent à stocker les types des propriétés du .config selon leur architecture et la version du kernel (tentative de future proofing de ma part), pour la génération du CSV (on ne peut pas déduire les types des propriétés si elles ne sont pas présente dans le .config, et donc connaître leurs valeurs par défaut).

Le projet [Kanalyzer](https://github.com/TuxML/Kanalyser) permet de remplir ces tables.

**Comment by ghost** [comment]
Quant à la vieille version de IrmaDB, elle est pour l'instant seulement utilisée par la branche master, qui sera bientôt mise à jour pour utiliser la nouvelle bdd Irma_prod, une fois les conflits réglés.
