### ISSUE TITLE
No documentation for TPDIM.py

### ISSUE THREAD

**Issue by acherm** [TuxML/ProjetIrma#61]
Toujours pas de doc pour TPDIM donc très difficile de l'utiliser. 

J'essaie de deviner le sens des paramètres (apparemment il faut générer un docker file avec -g et ensuite builder avec -b en faisant l'hypothèse qu'on a quelque part un dossier linux-4....) 

Merci de formuler les **prérequis** et la suite de commande qui va bien quelque chose comme: 
wget ...
python3 TPDIM.py -g ... 
python3 TPDIM.py -b ...

de sorte qu'en une ligne on puisse regénérer l'image facilement

**Comment by Heartbroken-Git** [comment]
Effectivement on a un gros travail de documentation à faire, on a déjà indiqué par l'issue #51 une première idée de production de documentation et la PR #58 prévoit une refonte du `README.md` :)

**Comment by Heartbroken-Git** [comment]
Le `README.md` a été édité avec quelques informations sommaires sur `TPDIM.py` et une documentation plus complète devrait arriver

**Comment by acherm** [comment]
Je propose de compléter la documentation et de la rendre plus **concrète** en expliquant comment mettre à jour l'image Docker (avec tous les prérequis qui vont bien): 
 * si on veut rajouter une dépendance Debian dans l'image Docker 
 * si on veut mettre à jour l'image suite à un commit sur la branche "dev" 
 * si on veut construire l'image "from scratch" (generate, build, sans linux-4.1.3...) 

en gros, tous les membres de TuxML peuvent avoir besoin d'avoir la main sur le build/push du Docker: ce serait bien qu'ils aient la commande magique (ou les commandes magiques) pour y parvenir
