### ISSUE TITLE
MLfood error at the end (despite successfully sent to DB) 

### ISSUE THREAD

**Issue by acherm** [TuxML/ProjetIrma#62]
Erreur mineure certainement: 

[+] 2018-03-28 12:37:12 | Successfully sent info to db
Starting tuxml.py ...

Fetch logs and .config file to the folder ./Logs/20180328_122348

Cleaning containers . . .
2cf0a8ee4940
Error response from daemon: You cannot remove a running container 3d72d4586a77d8dd1722b399857ab093b5d9318b261c4c1202d1f8892127b372. Stop the container before attempting removal or force remove
Clean done!

==========================================

Your tamago... database Irma_DB ate 1 compilation data, come back later to feed it!

**Comment by Heartbroken-Git** [comment]
J'assigne @CaptainMexiko comme il semblerait que ce soit un problème Docker.

**Comment by alemasle** [comment]
La commande lancée correspondait au lancement sur une image docker trop vieille avec des fichiers ancien ne fonctionnant plus et qui doit être mis à jour ( voir #58 ) l'erreur viens surement du fait que la commande ./MLfood.py n'avais pas le paramètre "--dev" qui est pour l'instant indispensable.
