### ISSUE TITLE
Hardware details (type of disk) failed and crashed the program 

### ISSUE THREAD

**Issue by acherm** [TuxML/ProjetIrma#63]
Le log ci-dessous (sur une machine "différente" de notre mini-grille à DiverSE) 

De manière générale:
 * il faut rendre plus robuste les procédures de récupérations (eg il faut vérifier en amont que la commande ou le fichier existe)
 * si on n'arrive pas à récupérer les infos, avoir un code spécifique (-1?)  
 * il faut réfléchir peut-être à des moyens plus "standards" de récupérer ce genre d'infos...  
 * expérimenter et recommencer 

```
cat: /sys/block/mapper/queue/rotational: No such file or directory
Traceback (most recent call last):
  File "/TuxML/tuxml.py", line 270, in <module>
    main()
  File "/TuxML/tuxml.py", line 241, in main
    targs.args_handler()
  File "/TuxML/tuxml_argshandler.py", line 102, in args_handler
    tset.NB_CORES = int(tenv.get_hardware_details()["cpu_cores"])
  File "/TuxML/tuxml_environment.py", line 117, in get_hardware_details
    "mechanical_drive": __get_type_of_disk()
  File "/TuxML/tuxml_environment.py", line 66, in __get_type_of_disk
    result = subprocess.check_output(["cat", "/sys/block/{}/queue/rotational".format(disk)], universal_newlines=True)
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['cat', '/sys/block/mapper/queue/rotational']' returned non-zero exit status 1

Fetch logs and .config file to the folder ./Logs/20180329_040730
Error response from daemon: lstat /var/lib/docker/aufs/mnt/01bd3d1be84308302911be491e84beed4306b638a0a485fd9e531035b1ff56c6/TuxML/linux-4.13.3/logs/std.log: no such file or directory
Error response from daemon: lstat /var/lib/docker/aufs/mnt/01bd3d1be84308302911be491e84beed4306b638a0a485fd9e531035b1ff56c6/TuxML/linux-4.13.3/logs/err.log: no such file or directory
Error response from daemon: lstat /var/lib/docker/aufs/mnt/01bd3d1be84308302911be491e84beed4306b638a0a485fd9e531035b1ff56c6/TuxML/linux-4.13.3/.config: no such file or directory

Cleaning containers . . .
3456c4a28dd8
Clean done!
```

Et en effet le fichier n'existe pas: 
```
ls /sys/block/
dm-0  dm-1  loop0  loop1  loop2  loop3  loop4  loop5  loop6  loop7  ram0  ram1  ram10  ram11  ram12  ram13  ram14  ram15  ram2  ram3  ram4  ram5  ram6  ram7  ram8  ram9  sda
```

**Comment by acherm** [comment]
à lire peut-être: https://unix.stackexchange.com/questions/52215/determine-the-size-of-a-block-device

**Comment by acherm** [comment]
je suggère d'utiliser cette librairie: 
https://github.com/giampaolo/psutil 

pour valider ce choix, je propose de fixer le bug ici:
https://github.com/TuxML/ProjetIrma/blob/dev/core/tuxml_environment.py#L71

en utilisant les facilités de l'API
http://psutil.readthedocs.io/en/latest/#disks

**Comment by micleb** [comment]
J'assigne @BzhErlb, c'est lui qui s'occupe de cette partie de TuxML

**Comment by fahimmerzouk** [comment]
Sur notre environnement, ça marche bien.
Pouvez vous tester de votre coté et nous faire un retour?

**Comment by fahimmerzouk** [comment]
Ps: il suffit juste d'appeler python3 tuxml_environnement.py
il n'y a pas besoin de lancer toute une compilation

**Comment by acherm** [comment]
cela semble marcher. Attention: il faut installer psutil avec python3/pip3

**Comment by acherm** [comment]
C'est une machine avec un disque dur SSD je pense 

cat: /sys/block/mapper/queue/rotational: No such file or directory
cat: /sys/block/mapper/queue/rotational: No such file or directory
Traceback (most recent call last):
  File "/TuxML/tuxml_environment.py", line 107, in __get_type_of_disk
    result = subprocess.check_output(["cat", "/sys/block/{}/queue/rotational".format(disk)], universal_newlines=True)
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['cat', '/sys/block/mapper/queue/rotational']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/TuxML/tuxml.py", line 285, in <module>
    main()
  File "/TuxML/tuxml.py", line 255, in main
    targs.args_handler()
  File "/TuxML/tuxml_argshandler.py", line 102, in args_handler
    tset.NB_CORES = int(tenv.get_hardware_details()["cpu_cores"])
  File "/TuxML/tuxml_environment.py", line 165, in get_hardware_details
    "mechanical_drive": __get_type_of_disk()
  File "/TuxML/tuxml_environment.py", line 112, in __get_type_of_disk
    result = subprocess.check_output(["cat", "/sys/block/{}/queue/rotational".format(disk)], universal_newlines=True)
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['cat', '/sys/block/mapper/queue/rotational']' returned non-zero exit status 1

(note pour moi-même: 10.0.0.7)

**Comment by BzhErlb** [comment]
Est-ce que vous pouvez faire le test suivant sur la même machine svp : 
Entrez dans l’interpréteur python3 et faites import psutil puis envoyez ici ce que renvoie : 

- psutil.disk_partitions()

Sur mon container docker de test psutil ne me renvoie que le (vrai) disque sur lequel il se trouve mais je soupçonne que ce n'est pas le cas dans votre environnement, sûrement dû à des spécificités des grilles. Savoir comment se comporte psutil sur les grilles nous permettrait d'y voir plus claire.

**Comment by acherm** [comment]
>>> psutil.disk_partitions()
[sdiskpart(device='/dev/mapper/node6--vg-root', mountpoint='/etc/resolv.conf', fstype='ext4', opts='rw,relatime,errors=remount-ro,data=ordered'), sdiskpart(device='/dev/mapper/node6--vg-root', mountpoint='/etc/hostname', fstype='ext4', opts='rw,relatime,errors=remount-ro,data=ordered'), sdiskpart(device='/dev/mapper/node6--vg-root', mountpoint='/etc/hosts', fstype='ext4', opts='rw,relatime,errors=remount-ro,data=ordered')]

**Comment by acherm** [comment]
par contre il n'y avait pas psutil d'installer sur l'image Docker tuxml/tuxmldebian:dev.... très curieux j'investigue

**Comment by acherm** [comment]
ubuntu@node6:~/mathieu-klinux$ sudo docker run -it tuxml/tuxmldebian:dev
root@02d699d94e62:/# python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.disk_partitions()
[sdiskpart(device='/dev/mapper/node6--vg-root', mountpoint='/etc/resolv.conf', fstype='ext4', opts='rw,relatime,errors=remount-ro,data=ordered'), sdiskpart(device='/dev/mapper/node6--vg-root', mountpoint='/etc/hostname', fstype='ext4', opts='rw,relatime,errors=remount-ro,data=ordered'), sdiskpart(device='/dev/mapper/node6--vg-root', mountpoint='/etc/hosts', fstype='ext4', opts='rw,relatime,errors=remount-ro,data=ordered')]

**Comment by BzhErlb** [comment]
Votre machine doit sûrement utiliser LVM. Vous confirmez?

C'est gênant parce que visiblement la "vraie" partition n’appairait même pas dans la liste avec .psutil.disk_partitions(). Il va falloir trouver un autre moyen dans ce cas de figure.

Pouvez vous envoyer ce que retourne les commandes **df**, **lsblk**  et **cat /proc/mounts**.

Vous pouvez aussi tenter **dmsetup ls**, **pvs**, **lvdisplay**.  Si dmsetup ls ne fonctionne pas il est probable que cela viennent des droits autorisés (voir [lien](https://stackoverflow.com/questions/25892586/can-we-create-volumes-inside-docker-container)), on devrait pouvoir tester sur un container construit avec la commande sudo docker run **--cap-add=ALL** [Nom_Image]

**Comment by acherm** [comment]
root@1baa2fc8b4b4:/# df
Filesystem                 1K-blocks      Used Available Use% Mounted on
none                       222916212 169034760  42534920  80% /
tmpfs                        3575724         0   3575724   0% /dev
tmpfs                        3575724         0   3575724   0% /sys/fs/cgroup
/dev/mapper/node6--vg-root 222916212 169034760  42534920  80% /etc/hosts
shm                            65536         0     65536   0% /dev/shm

root@1baa2fc8b4b4:/# lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0 223.6G  0 disk
|-sda1   8:1    0   487M  0 part
|-sda2   8:2    0     1K  0 part
`-sda5   8:5    0 223.1G  0 part

root@1baa2fc8b4b4:/# cat /proc/mounts
none / aufs rw,relatime,si=3d31942673c3124d,dio,dirperm1 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev tmpfs rw,nosuid,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666 0 0
sysfs /sys sysfs ro,nosuid,nodev,noexec,relatime 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,relatime,mode=755 0 0
pids /sys/fs/cgroup/pids cgroup ro,nosuid,nodev,noexec,relatime,pids 0 0
hugetlb /sys/fs/cgroup/hugetlb cgroup ro,nosuid,nodev,noexec,relatime,hugetlb 0 0
blkio /sys/fs/cgroup/blkio cgroup ro,nosuid,nodev,noexec,relatime,blkio 0 0
freezer /sys/fs/cgroup/freezer cgroup ro,nosuid,nodev,noexec,relatime,freezer 0 0
devices /sys/fs/cgroup/devices cgroup ro,nosuid,nodev,noexec,relatime,devices 0 0
perf_event /sys/fs/cgroup/perf_event cgroup ro,nosuid,nodev,noexec,relatime,perf_event 0 0
memory /sys/fs/cgroup/memory cgroup ro,nosuid,nodev,noexec,relatime,memory 0 0
cpuset /sys/fs/cgroup/cpuset cgroup ro,nosuid,nodev,noexec,relatime,cpuset 0 0
net_cls,net_prio /sys/fs/cgroup/net_cls,net_prio cgroup ro,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cpu,cpuacct /sys/fs/cgroup/cpu,cpuacct cgroup ro,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
name=systemd /sys/fs/cgroup/systemd cgroup ro,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
cgroup /sys/fs/cgroup/systemd cgroup ro,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup ro,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup ro,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/cpuset cgroup ro,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/memory cgroup ro,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/perf_event cgroup ro,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/devices cgroup ro,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/freezer cgroup ro,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/blkio cgroup ro,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup ro,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/pids cgroup ro,nosuid,nodev,noexec,relatime,pids 0 0
mqueue /dev/mqueue mqueue rw,nosuid,nodev,noexec,relatime 0 0
/dev/mapper/node6--vg-root /etc/resolv.conf ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
/dev/mapper/node6--vg-root /etc/hostname ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
/dev/mapper/node6--vg-root /etc/hosts ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
shm /dev/shm tmpfs rw,nosuid,nodev,noexec,relatime,size=65536k 0 0
devpts /dev/console devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
proc /proc/asound proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/bus proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/fs proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/irq proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/sys proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/sysrq-trigger proc ro,nosuid,nodev,noexec,relatime 0 0
tmpfs /proc/kcore tmpfs rw,nosuid,mode=755 0 0
tmpfs /proc/timer_stats tmpfs rw,nosuid,mode=755 0 0
tmpfs /proc/sched_debug tmpfs rw,nosuid,mode=755 0 0

root@1baa2fc8b4b4:/# dmsetup ls
/dev/mapper/control: open failed: Operation not permitted
Failure to communicate with kernel device-mapper driver.
Check that device-mapper is available in the kernel.
Incompatible libdevmapper 1.02.137 (2016-11-30) and kernel driver (unknown version).
Command failed

root@1baa2fc8b4b4:/# pvs
bash: pvs: command not found

root@1baa2fc8b4b4:/# lvdisplay
bash: lvdisplay: command not found

**Comment by acherm** [comment]
docker run -it --cap-add=ALL tuxml/tuxmldebian:dev
root@cae6e69db99b:/# dmsetup ls
/dev/mapper/control: open failed: Operation not permitted
Failure to communicate with kernel device-mapper driver.
Check that device-mapper is available in the kernel.
Incompatible libdevmapper 1.02.137 (2016-11-30) and kernel driver (unknown version).
Command failed

**Comment by acherm** [comment]
merci de l'expertise en tout cas sur les disques durs ;) 
peut-être est-ce un problème très spécifique (le cas ne s'est rencontré que sur une seule machine, ce n'est pas hyper bloquant) 

c'est cool si on peut régler le problème, mais de manière générale je me dis qu'un bon try/catch ne serait pas déconnant car on sent bien que la procédure peut échouer à pas mal d'endroits.

**Comment by alemasle** [comment]
Je viens de tomber sur un cas similaire sur IGRIDA: 

```
cat: /sys/block/sda/queue/rotational: No such file or directory
cat: /sys/block/mapper/queue/rotational: No such file or directory
Traceback (most recent call last):
  File "/TuxML/tuxml_environment.py", line 133, in __get_type_of_disk
    result = subprocess.check_output(["cat", "/sys/block/sda/queue/rotational".format(disk)], universal_newlines=True)
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['cat', '/sys/block/sda/queue/rotational']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/TuxML/tuxml.py", line 341, in <module>
    main()
  File "/TuxML/tuxml.py", line 298, in main
    targs.args_handler()
  File "/TuxML/tuxml_argshandler.py", line 140, in args_handler
    tset.NB_CORES = int(tenv.get_hardware_details()["cpu_cores"])
  File "/TuxML/tuxml_environment.py", line 198, in get_hardware_details
    "mechanical_drive": __get_type_of_disk()
  File "/TuxML/tuxml_environment.py", line 138, in __get_type_of_disk
    result = subprocess.check_output(["cat", "/sys/block/{}/queue/rotational".format(disk)], universal_newlines=True)
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['cat', '/sys/block/mapper/queue/rotational']' returned non-zero exit status 1

```

**Comment by alemasle** [comment]
J'en cherche la cause et/ou la corrige si possible

**Comment by alemasle** [comment]
Une correction est proposée dans `tuxml_environnement.py`, l'erreur semble avoir disparu du début de la compilation. Je fermerai l'issue si à la fin du processus si elle ne s'est pas représentée dans ce cas.

**Comment by alemasle** [comment]
La compilation sur la grille s'est terminée sans encombre, je ferme l'issue
