### ISSUE TITLE
MLfood / comp incrémetale 

### ISSUE THREAD

**Issue by acherm** [TuxML/ProjetIrma#64]
J’ai tenté MLfood.py 1 3 --dev cela n’a pas fait de compilation incrémentale... (il s’est arrêté à 1 compilation et bye) 

le `incrN` avec argv[2] est curieux (il faut utiliser proprement la librairie d'arguments Python: cela aura le mérite de faciliter l'implémentation et de permettre l'ajout d'un nom au paramètres --incremental)

**Comment by alemasle** [comment]
Avez-vous l'ouput.log de cet essai ? j'aimerais le voir afin d'en déterminer la cause

**Comment by alemasle** [comment]
[UPDATE] Un correctif à été fait, pouvez-vous vérifier que le comportement du programme de votre côté est tel que voulu ?

**Comment by acherm** [comment]
Cela semble mieux en effet, merci. 
dans Incremental_Compilations (base de données) on a: 
144 | 139
142 | 139
141 | 139
mais dans Compilations les 141, 142, et 144 n'ont pas le mode incremental_mod à 1 
les temps de compilation sont élevés / normaux donc difficile d'établir si cela a vraiment marché cc @micleb

**Comment by micleb** [comment]
J'ai trouvé d'où vient le problème.

Déjà, il faut savoir que je ne considère pas la première compilation (base config == #139 dans votre exemple) comme incrémentale. Étant donné qu'elle n'utilise aucun fichier objet issu d'une précédente compilation.
Tandis que les autres (#141, #142, #143 dans votre exemple) sont bien incrémentales.

Donc je mets à 1 la variable "INCREMENTAL_MOD" seulement quand on lance les compilations incrémentales et non la compilation d'origine (base config) : 
```
for i in range(0, tset.INCITERS):
        tset.INCREMENTAL_MOD = 1
        tcom.pprint(2, "Launching incremental compilation #" + str(i + 1))
        gen_config()
        if launcher() < 0:
            sys.exit(-1)
```

Sauf que je ne récupère qu'une fois l'environnement, où la variable incremental_mod est stockée : au début du programme et avant la compilation d'origine.
Donc à ce moment-là incremental_mod est à 0.

Je vais mettre à jour l'environnement dans la boucle ci-dessus et ça devrait corriger le problème.

Je fais quelques tests pour être sûr que ça fonctionne et le fix sera dispo dans mon prochain commit.

Concernant les temps élevés, je ne sais pas quoi dire. J'ai lancé 3 compilations incrémentales.
La compilation d'origine est à 12'00 et les 3 autres à 9'37, 8'35 et 5'22. De mon côté rien d'anormal.
