### ISSUE TITLE
No data sent to database because of boot checking 

### ISSUE THREAD

**Issue by acherm** [TuxML/ProjetIrma#65]
Le programme "crash" sur bootCheck au point de ne pas envoyer de données (avec une machine de la grille). 
J'ai lancé avec:
sudo python /home/tuxml/ProjetIrma/MLfood.py 1 --dev
(branche "dev") 

WARNING: missing /lib/modules/4.4.30-0-grsecM
Ensure all necessary drivers are built into the linux image!M
depmod: ERROR: could not open directory /lib/modules/4.4.30-0-grsec: No such file or directoryM
depmod: FATAL: could not search modules: No such file or directoryM
depmod: WARNING: could not open /var/tmp/mkinitramfs_UBCdQr/lib/modules/4.4.30-0-grsec/modules.order: No such file or directoryM
depmod: WARNING: could not open /var/tmp/mkinitramfs_UBCdQr/lib/modules/4.4.30-0-grsec/modules.builtin: No such file or directoryM
Traceback (most recent call last):M
  File "/TuxML/tuxml.py", line 270, in <module>M
    main()M
  File "/TuxML/tuxml.py", line 249, in mainM
    tset.BASE_CONFIG_ID = launcher()M
  File "/TuxML/tuxml.py", line 217, in launcherM
    status = tbch.boot_try()M
  File "/TuxML/tuxml_bootCheck.py", line 29, in boot_tryM
    outFile = open("serial.out",mode='r')M
FileNotFoundError: [Errno 2] No such file or directory: 'serial.out'M

**Comment by Heartbroken-Git** [comment]
Il faut que je me renseigne plus mais vraisemblablement c'est encore et toujours `mkinitramfs` qui ne marche pas. Cette vieille méthode est obsolète et va disparaître avec la v0 du nouveau `bootCheck()`. Cependant sur les autres machines ça ne faisait pas planter le programme. Il serait intéressant de comprendre pourquoi ça le fait dans ce cas précis pour l'éviter s'il devait revenir dans le futur.

En tout cas cette issue rend plus urgent encore l'ajout du prérequis de la v0 dans l'image de Docker et les tests de la V0 qui est normalement finie.

**Comment by acherm** [comment]
Il faut avoir une approche plus "défensive" et catcher le crash (avec code de retour spécifique, quelque chose comme -3 ou -4). C'est un peu la même histoire qu'avec hardware_details: la procédure peut s'écrouler/crasher, mais un rage quit sans rien c'est dommage car on perd des informations. 

Après +1 avec la roadmap sur le boot

**Comment by Heartbroken-Git** [comment]
Il y avait un système récupérant un code d'erreur du _subprocess_ et retournant un code spécifique plutôt que de planter le programme. Cependant il semblerait qu'il ne fonctionne plus. Peut-être suite à la redirection du flux `stderr` du _subprocess_ par @micleb pour l'affichage ?
A tester en tout cas. :thinking:

**Comment by micleb** [comment]
J'ai ajouté un try/except au tour du subprocess.call(["mkinitramfs", ...]) pour corriger le problème.

Voir commit b3d8c8b2b1900b20f278db5f5e2f69f8c213527c

J'attends les résultats de quelques tests avant de fermer l'issue.

**Comment by acherm** [comment]
[2018-04-04 13:56:51 GMT] [boot_try] Launching boot test on kernel
WARNING: missing /lib/modules/4.4.30-0-grsec
Ensure all necessary drivers are built into the linux image!
depmod: ERROR: could not open directory /lib/modules/4.4.30-0-grsec: No such file or directory
depmod: FATAL: could not search modules: No such file or directory
depmod: WARNING: could not open /var/tmp/mkinitramfs_lylbXh/lib/modules/4.4.30-0-grsec/modules.order: No such file or directory
depmod: WARNING: could not open /var/tmp/mkinitramfs_lylbXh/lib/modules/4.4.30-0-grsec/modules.builtin: No such file or directory
Traceback (most recent call last):
  File "/TuxML/tuxml.py", line 270, in <module>
    main()
  File "/TuxML/tuxml.py", line 249, in main
    tset.BASE_CONFIG_ID = launcher()
  File "/TuxML/tuxml.py", line 217, in launcher
    status = tbch.boot_try()
  File "/TuxML/tuxml_bootCheck.py", line 29, in boot_try
    outFile = open("serial.out",mode='r')
FileNotFoundError: [Errno 2] No such file or directory: 'serial.out'

**Comment by Heartbroken-Git** [comment]
Alors ça plante en ne détectant pas le fichier `serial.out`. C'est normal car celui est généré à l'exécution de qemu, or celui-cli ne s'exécute pas comme l'étape précédente (le initramfs) ne s'exécute pas non plus. Il faut que je modifie le fix de @micleb qui ne doit pas arrêter le programme alors qu'il détecte l'erreur.

**Comment by alemasle** [comment]
Problème résolu
