### ISSUE TITLE
Docker image build: still not working 

### ISSUE THREAD

**Issue by acherm** [TuxML/ProjetIrma#69]
TPDIM.py -b debian -t dev
ADD failed: stat /var/lib/docker/tmp/docker-builder818467330/gcc-learn/ConfigFile: no such file or directory

et oui il n'y a pas de ConfigFile dans gcc-learn 
(branche dev)

**Comment by acherm** [comment]
J'ai commenté la ligne qui causait l'erreur (see commit f3997cff9a4b2168ab4a8aaa4023a833089c0d75) 

Après j'ai exécuté ces commandes dans cet ordre: 
python3 TPDIM.py -g debian -dep dependences.txt -t dev
python3 TPDIM.py -b debian -t dev
python3 TPDIM.py -p debian -t dev

(l'ordre inverse de la doc!?) 

normalement l'image est à jour

**Comment by acherm** [comment]
Still the issue with gcc-learn/ConfigFile (cc @Aexelion) 
Now we can update the image in one shot:
python3 TPDIM.py -a debian -t dev

**Comment by alemasle** [comment]
GCC-learn est un dossier qui a disparu lors de commits et de merges imparfait, il n'est pas important pour le projet, de plus la commande TPDIM a été modifiée avec l'ajout de l'option 'a' permettant de construire l'image en une seule fois.
