### ISSUE TITLE
Crash boot time

### ISSUE THREAD

**Issue by acherm** [TuxML/ProjetIrma#72]
sur une machine de la grille (branche dev)
python3 MLfood.py 1 --dev

[2018-04-05 13:46:45 GMT] [boot_try] Launching boot test on kernel
WARNING: missing /lib/modules/4.4.30-0-grsec
Ensure all necessary drivers are built into the linux image!
depmod: ERROR: could not open directory /lib/modules/4.4.30-0-grsec: No such file or directory
depmod: FATAL: could not search modules: No such file or directory
depmod: WARNING: could not open /var/tmp/mkinitramfs_X91CSk/lib/modules/4.4.30-0-grsec/modules.order: No such file or directory
depmod: WARNING: could not open /var/tmp/mkinitramfs_X91CSk/lib/modules/4.4.30-0-grsec/modules.builtin: No such file or directory
0
Traceback (most recent call last):
  File "/TuxML/tuxml.py", line 285, in <module>
    main()
  File "/TuxML/tuxml.py", line 263, in main
    tset.BASE_CONFIG_ID = launcher()
  File "/TuxML/tuxml.py", line 231, in launcher
    status = tbch.boot_try()
  File "/TuxML/tuxml_bootCheck.py", line 33, in boot_try
    outFile = open("serial.out",mode='r')
FileNotFoundError: [Errno 2] No such file or directory: 'serial.out'

**Comment by acherm** [comment]
Toujours le problème avec serial.out 
Je ne sais pas si cela joue, mais je lance MLfood dans un docker (docker qui lance un docker)... je ferai mieux plus tard mais normalement ça devrait passer

Clairement faut "catcher" le crash de nouveau ;) 
après pourquoi cela ne marche pas je ne sais pas

**Comment by Heartbroken-Git** [comment]
Semblable à #65.
C'est assez surprenant que ça déconne encore. on catchait pourtant toutes les exceptions lors de l’appel à `mkinitramfs`. Il faut croire que quand il plante ça ne lève aucune exception :/
Je vais bidouiller un fix rapide pour ça remarche enfin.

**Comment by Heartbroken-Git** [comment]
Plus qu'à mettre à jour l'image Docker dev et à tester ce fix sur la grille.
