### ISSUE TITLE
Make randconfig: warnings et output.log 

### ISSUE THREAD

**Issue by acherm** [TuxML/ProjetIrma#73]
Lorsqu'on utilise make randconfig il n'est pas rare de rencontrer des warnings:
 
KCONFIG_SEED=0x4E78791F
warning: (X86_INTEL_LPSS && INTEL_SOC_DTS_IOSF_CORE && SND_SST_IPC_ACPI && MMC_SDHCI_ACPI) selects IOSF_MBI which has unmet direct dependencies (PCI)

Un bon point: on "log" bien ce genre de messages dans le dossier Logs. 
**Par contre output.log n'est pas envoyé dans la base de données ?!!! Pourquoi ?** 

Ces warnings sont "intrigants": avec output.log on pourrait certainement analyser ces messages d'erreurs et essayer de comprendre dans quel cas cela se produit. 

Il est probable, mais à vérifier, que ce soit à cause de CONFIG_EXPERIMENTAL:
https://kernelnewbies.org/FAQsInProgress

**A-t-on des statistiques sur le nombre de fois où CONFIG_EXPERIMENTAL est actif dans notre jeu de données actuel (~2000 entrées du CSV)?**

**Comment by micleb** [comment]
J'ai assigné Alexis et moi pour la récupération de tuxlog ainsi que Pierre et Dorian pour les statistiques de CONFIG_EXPERIMENTAL

**Comment by FAMILIAR-project** [comment]
output.log: DONE

reste ouvert l'issue sur CONFIG_EXPERIMENTAL mais c'est bien bien moins urgent

**Comment by alemasle** [comment]
Le fichier output.log est maintenant créé à l'intérieur du conteneur Docker et est envoyé à la base de données par le script `runandlog.py`.

**Comment by FAMILIAR-project** [comment]
Oui, merci. Je pense qu'on peut clore cette "issue" j'en crée une autre pour CONFIG_EXPERIMENTAL qui n'a pas trop à voir avec le output.log ;)
