### ISSUE TITLE
Docker et -it

### ISSUE THREAD

**Issue by acherm** [TuxML/ProjetIrma#74]
L'option -it dans MLfood pour appeler docker peut poser problème sur certains environnements... 
J'ai eu le problème sur la grille. 

Je propose d'enlever le -i et de ne garder que -t (cf https://stackoverflow.com/questions/43099116/the-input-device-is-not-a-tty)

**Comment by ghost** [comment]
C'est normal, le -i veut dire que l'on lance le docker avec interaction, donc sur une machine d'une grille ça plante. J'ai eu le même problème mais je me rappel pas comment j'ai fait pour le réparer.

**Comment by acherm** [comment]
docker run -t ....
au lieu de docker run -it 
https://github.com/TuxML/ProjetIrma/blob/dev/MLfood.py#L152 
b5ea2e3  

Je teste / mets à jour l'image Docker dans quelques minutes

**Comment by acherm** [comment]
Test sur la grille + MacOS concluant.

**Comment by alemasle** [comment]
En faite ça avait déjà été corrigé mais il semble que les merges et problemes ont fait un rollback de cette ligne
