### ISSUE TITLE
50+ compilations (y/n)

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#75]
Are-you sure you want to start 50 compilation? (y/n)
Canceling it would take as much Ctrl+C as the remaining number of compilations.

Traceback (most recent call last):
  File "MLfood.py", line 189, in <module>
    mlfood()
  File "MLfood.py", line 111, in mlfood
    ok = input()
  File "<string>", line 0

I cannot answer "y" (it does not handle properly the input) 
note: it happens only on one machine

**Comment by alemasle** [comment]
Etrange bug, la machine avait une spécificité ?

**Comment by alemasle** [comment]
Cette partie reste en commentaire, elle sera décommenté et complétée par un paramètre permettant de sauter cette étape par la suite.

**Comment by FAMILIAR-project** [comment]
Du coup c'est pas vraiment une issue fermée non?

**Comment by alemasle** [comment]
L'option ''-y' a été ajouté, lors du lancement de compilations en grand nombre, si l'option -y est activée il n'y aura aucune vérification auprès de l'utilisateur sur sa certitude à lancer plus de 50 compilations à la suite.

**Comment by alemasle** [comment]
L'option "--force-compilation-limits" a été ajoutée, permettant de passer la vérification auprès de l'utilisateur et donc la compilation à grande échelle. Une vérification de l'input a été ajoutée, permettant de redemander en cas d'input vide par erreur.
