### ISSUE TITLE
Compilation time is very^very high (suspicious) 

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#76]
Look at cids:
654
652
651
650
more than 20000! 

I don't know why... 
Two hypotheses:
 * we don't properly compute compilation time (what's strange is that compilation dates are quite close eg 2018-04-13 13:33 and 2018-04-13 13:29... only 4 minutes) 
 * the process for compiling takes too much time 

I have observed many times these days that the process can be somehow "suspended" on 
update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode

(at least it does not make any apparent progress for a while, suggesting that nothing happens)

more details below:
The following additional packages will be installed:
  g++-6 libstdc++-6-dev
Suggested packages:
  g++-multilib g++-6-multilib gcc-6-doc libstdc++6-6-dbg libstdc++-6-doc
The following NEW packages will be installed:
  g++ g++-6 libstdc++-6-dev
0 upgraded, 3 newly installed, 0 to remove and 2 not upgraded.
Need to get 8516 kB of archives.
After this operation, 39.8 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian stretch/main amd64 libstdc++-6-dev amd64 6.3.0-18+deb9u1 [1420 kB]
Get:2 http://deb.debian.org/debian stretch/main amd64 g++-6 amd64 6.3.0-18+deb9u1 [7094 kB]
Get:3 http://deb.debian.org/debian stretch/main amd64 g++ amd64 4:6.3.0-4 [1546 B]
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 3.)
debconf: falling back to frontend: Readline
Fetched 8516 kB in 0s (8602 kB/s)
Selecting previously unselected package libstdc++-6-dev:amd64.
(Reading database ... 24181 files and directories currently installed.)
Preparing to unpack .../libstdc++-6-dev_6.3.0-18+deb9u1_amd64.deb ...
Unpacking libstdc++-6-dev:amd64 (6.3.0-18+deb9u1) ...
Selecting previously unselected package g++-6.
Preparing to unpack .../g++-6_6.3.0-18+deb9u1_amd64.deb ...
Unpacking g++-6 (6.3.0-18+deb9u1) ...
Selecting previously unselected package g++.
Preparing to unpack .../g++_4%3a6.3.0-4_amd64.deb ...
Unpacking g++ (4:6.3.0-4) ...
Setting up libstdc++-6-dev:amd64 (6.3.0-18+deb9u1) ...
Setting up g++-6 (6.3.0-18+deb9u1) ...
Setting up g++ (4:6.3.0-4) ...
update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode

**Comment by FAMILIAR-project** [comment]
An example: for cid 668
compilation time is 31674.1

9 hours? very strange 

logs attached 

[c668.zip](https://github.com/TuxML/ProjetIrma/files/1908354/c668.zip)

**Comment by FAMILIAR-project** [comment]
I don't have an explanation but I suspect a "crazy" MLfood process 
It seems no longer active 

I plan to remove such suspicious entries in the database 
I will try to replicate then

**Comment by alemasle** [comment]
Is there an advancement on this issue ? Did it came back since then ?

**Comment by alemasle** [comment]
There was not other "strange" compilations time since those cid. So may i close this issue ? I think it was a bad manipulation or a specific machine that stop working for minutes because of some functionality.

**Comment by FAMILIAR-project** [comment]
Yes! We need to clean the database for the early CIDs but that's another story (issue) ;-)
