### ISSUE TITLE
Infinite loop? (compilation + packages) 

### ISSUE THREAD

**Issue by acherm** [TuxML/ProjetIrma#77]
I have used 4 machines (for 100 compilations) and they seem to "stop". 
Is it possible to have an infinite loop when updating packages? 

Attached are 4 logs (1 log per machine, in zip format) 
[job.4694642.output.zip](https://github.com/TuxML/ProjetIrma/files/1939611/job.4694642.output.zip)
[job.4694645.output.zip](https://github.com/TuxML/ProjetIrma/files/1939614/job.4694645.output.zip)
[job.4694644.output.zip](https://github.com/TuxML/ProjetIrma/files/1939615/job.4694644.output.zip)
[job.4694643.output.zip](https://github.com/TuxML/ProjetIrma/files/1939616/job.4694643.output.zip)

**Comment by acherm** [comment]
An example: 

ii  linux-libc-dev-sh4-cross          4.9.25-1cross1                          all          Linux Kernel Headers for development (for cross-compiling)
ii  linux-libc-dev-sparc64-cross      4.9.25-1cross1                          all          Linux Kernel Headers for development (for cross-compiling)
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

and infinitely

**Comment by ghost** [comment]
On pourrait mettre en place un compteur, si on reste a la même étape 30 fois on dump la compil avec le code d'erreur -5 (exemple)

**Comment by acherm** [comment]
Ta suggestion me semble très intéressante. Peut-être même envisager un "timeout". 

J'ai eu encore le problème hier soir sur 3 autres machines. Je me dis que cela vient peut-être du réseau (eg la machine de la grille n'arrive pas à mettre à jour apt-get).

**Comment by alemasle** [comment]
Il serait surement possible de résoudre le problème en utilisant "apt full-upgrade" afin de réellement installer les paquets ainsi que les paquets considérés "non upgradés", j'ai déjà constaté que "apt upgrade" laissant parfois ces "non upgradés" et donc disait toujours que des paquets étaient à installer. "full-upgrade" ferait bien la mise à jour du paquet bloquant.

**Comment by FAMILIAR-project** [comment]
ok, suggestion intéressante! mais le apt full-upgrade à chaque fois ce serait assez coûteux je trouve... faudrait l'automatiser a priori/avant dans le Dockerfile idéalement. 
et voir si ça résout une partie du problème 

fondamentalement je pense que notre algo. d'essai/erreur peut ne pas terminer, ce serait intéressant d'implémenter un espèce de timeout... 

En l'état, ce qui serait pertinent IMHO c'est de re-rencontrer le problème de ton côté (par exemple en lançant des compilations toute la nuit sur certaines machines et au petit matin se rendre compte qu'elle a tourné dans le vide à partir de 2h du mat' ;-)) et de le caractériser plus finement -- chose que je n'ai pas vraiment réussi à faire faute de temps

**Comment by alemasle** [comment]
En deux nuits j'ai fait environ 300 compilations sur une seule machine mais ce problème ne s'est jamais montré puisque lorsque j'arrivais je vérifiais les heures de Logs justement et le dernier correspondait en général à moins de 15 minutes avant que j'arrive

**Comment by FAMILIAR-project** [comment]
ok, bonne nouvelle! 
peut-être est-ce lié à la grille (IGRIDA), car c'était là que j'avais rencontré le problème 

je propose de labelliser le problème comme une issue "grid" (à moyen terme on va déployer sur la grille et je soupçonne des issues spécifiques liées à la grille ;))
