### ISSUE TITLE
make mrproper?

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#80]
Après une compilation (et en mode non incrémental), on fait un make clean mais pas de make mrproper. 

status = subprocess.call(["make", "-C", tset.PATH, "clean"], stdout=tset.OUTPUT, stderr=tset.OUTPUT)

Pourtant d'après la documentation, cela semble être la méthode la plus complète/sûre/efficace:

`clean - Remove most generated files but keep the config and
        enough build support to build external modules
mrproper - Remove all generated files + config + various backup files`

Du coup, il va falloir vérifier certains résultats, car il se peut que nos résultats soient biaisés. 
Aussi, je propose:
 * de rajouter make mrproper 
 * de re-compiler certaines configurations et de vérifier qu'on obtient les mêmes tailles de kernel (malgré le fait de n'avoir pas fait de make mrproper)

**Comment by alemasle** [comment]
Je fais en ce moment des tests dessus, je prends deux .config et je les compiles de différentes manières (make clean, make mrproper)

**Comment by alemasle** [comment]
Chaque compilations "basique" est exécutée dans un nouveau conteneur indépendant des autres, les compilations incrémentales quant à elles, se servent des fichiers déjà compilés des précédentes compilations donc aucun `make clean` ou `make mrproper` n'est effectué, le `make clean` restant dans le code est un reste d'une étape de développement qui semble désormais obsolète et qui sera supprimé lorsque les tests seront terminés sur cette partie.
