### ISSUE TITLE
Size of the kernel

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#81]
Our method for computing the size of the kernel relies on this portion of code: 
https://github.com/TuxML/ProjetIrma/blob/dev/core/tuxml_sendDB.py#L44-L50

```
def get_kernel_size():
    possible_filenames = ["vmlinux", "vmlinux.bin", "vmlinuz", "zImage", "bzImage"]
    for filename in possible_filenames:
        full_filename = tset.PATH + "/" + filename
        if os.path.isfile(full_filename):
            return os.path.getsize(full_filename)
    return 0
```

It returns the size of the first file encountered in the list (otherwise 0).  

**I think it's an oversimplification and a mistake.** 

The kernel can be "compressed" using various methods/formats: 
https://github.com/torvalds/linux/blob/master/Makefile#L944-L949

The compression method is actually defined in .config 
https://github.com/torvalds/linux/blob/master/usr/Kconfig#L134

If I am not wrong, the compilation process will produce the compressed kernels (like vmlinux). 
And actually it can produce several kernel files (each per compression method). It seems the compression options are **not** mutually exclusive (you can activate several compression options in the same configuration). 
So at the end we can well have "bzImage" and "vmlinuz". 

The thing is that the compression method can vastly influence the size of the kernel; and we are mostly interested in understanding the effects of configuration options. 
At the moment, the way we compute the size of the kernel is too much dependent of the compression method. 

I think there are two action points to take here:
 * restructure the database schema in such a way we can clearly understand what compression method is used for size computation   
 * return **several sizes** (not only one size)
 * "rewrite/re-engineer" the current data and transform it according to the new schema 
 * I also suggest to activate **all** compression options per default in each configuration (it seems cheap)

**Comment by FAMILIAR-project** [comment]
(for better understanding the compilation process, see https://github.com/torvalds/linux/blob/master/usr/Makefile#L27-L30)

**Comment by FAMILIAR-project** [comment]
apparently BLK_DEV_INITRD should be activated https://github.com/torvalds/linux/blob/master/init/Kconfig#L999-L1018

**Comment by FAMILIAR-project** [comment]
https://github.com/torvalds/linux/blob/master/arch/x86/boot/compressed/Makefile

**Comment by FAMILIAR-project** [comment]
https://github.com/torvalds/linux/blob/master/scripts/Makefile.lib#L213

**Comment by FAMILIAR-project** [comment]
So my report. 

vmlinux is always produced. 
There are actually two vmlinux: 
root@3f9bf21d9893:/home/klinux/linux-4.13.3# ls -alrth arch/x86/boot/compressed/vmlinux
-rwxr-xr-x 1 root root 8.6M May 28 20:55 arch/x86/boot/compressed/vmlinux
root@3f9bf21d9893:/home/klinux/linux-4.13.3# ls -alrth vmlinux
-rwxr-xr-x 1 root root 42M May 28 20:54 vmlinux

Then you have specific compressed kernels (see below). 
You have basically **6 configuration options for compressing your kernel and the output is in arch/x86/boot/compressed/**

```
Kernel compression mode
  1. Gzip (KERNEL_GZIP)
  2. Bzip2 (KERNEL_BZIP2)
  3. LZMA (KERNEL_LZMA)
> 4. XZ (KERNEL_XZ)
  5. LZO (KERNEL_LZO) (NEW)
  6. LZ4 (KERNEL_LZ4)
choice[1-6?]:
```

We should not confuse them with configuration options related to initramfs (that are options for compressing the initram file system). 
Note that these 6 options are mutually exclusive. 

My understanding and experience show that we could:
 (1) compile the kernel (with GZIP says, the default)
 (2) modify the .config to activate other compression options, and then without make clean/mrproper, we can get a new compressed kernel file and compute its size. It is very cheap (a few seconds) since the compression option only occurs at the end of the making process 
 (3) continue with other compression options

At the end of the process, **for one configuration we could launch 5 "incremental" compilations and get 5 size measurements**. 

The next actions point is basically to implement this idea, specifically some tasks to do
 * redesign a bit the database to be able to encode new size measurements 
 * modify the get_kernel_size 
 * implement the automated modification of ".config" (with a rewrite)
 * instrument the iteration over all compression options
 * test, test, test

From a practical point of view, when the user wants to compile a specific configuration or launch an experiments, we will simply measure several sizes (and to do so, it's a bit technical but the user won't see it)



```
# CONFIG_KERNEL_XZ=y
root@3f9bf21d9893:/home/klinux/linux-4.13.3# ls -alrth arch/x86/boot/compressed/vmlinux.
vmlinux.bin     vmlinux.bin.xz  vmlinux.lds     vmlinux.lds.S   vmlinux.relocs
root@3f9bf21d9893:/home/klinux/linux-4.13.3# ls -alrth arch/x86/boot/compressed/vmlinux.bin
-rwxr-xr-x 1 root root 34M May 28 16:39 arch/x86/boot/compressed/vmlinux.bin
root@3f9bf21d9893:/home/klinux/linux-4.13.3# ls -alrth arch/x86/boot/compressed/vmlinux.bin.xz
-rw-r--r-- 1 root root 3.5M May 28 16:39 arch/x86/boot/compressed/vmlinux.bin.xz
root@3f9bf21d9893:/home/klinux/linux-4.13.3# ls -alrth vmlinux
-rwxr-xr-x 1 root root 47M May 28 16:39 vmlinux

# CONFIG_KERNEL_LZO=y
ls -alrth arch/x86/boot/compressed/vmlinux.bin.lzo
-rw-r--r-- 1 root root 5.7M May 28 19:05 arch/x86/boot/compressed/vmlinux.bin.lzo

root@3f9bf21d9893:/home/klinux/linux-4.13.3# diff .config .config.old
65,66c65,66
< CONFIG_KERNEL_LZMA=y
< # CONFIG_KERNEL_XZ is not set
---
> CONFIG_KERNEL_LZMA=y # is not set
> # CONFIG_KERNEL_XZ=y
root@3f9bf21d9893:/home/klinux/linux-4.13.3# ls -alrth arch/x86/boot/compressed/vmlinux.bin.lzma
-rw-r--r-- 1 root root 4.1M May 28 19:17 arch/x86/boot/compressed/vmlinux.bin.lzma

diff .config .config.old
64,65c64,65
< CONFIG_KERNEL_BZIP2=y
< # CONFIG_KERNEL_LZMA is not set
---
> CONFIG_KERNEL_BZIP2=y # is not set
> # CONFIG_KERNEL_LZMA=y
ls -alrth arch/x86/boot/compressed/vmlinux.bin.bz2
-rw-r--r-- 1 root root 5.1M May 28 19:19 arch/x86/boot/compressed/vmlinux.bin.bz2

root@3f9bf21d9893:/home/klinux/linux-4.13.3# diff .config .config.old
63,64c63,64
< CONFIG_KERNEL_GZIP=y
< # CONFIG_KERNEL_BZIP2 is not set
---
> CONFIG_KERNEL_GZIP=y # is not set
> # CONFIG_KERNEL_BZIP2=y

ls -alrth arch/x86/boot/compressed/vmlinux.bin.gz
-rw-r--r-- 1 root root 5.0M May 28 19:21 arch/x86/boot/compressed/vmlinux.bin.gz

ls -alrth arch/x86/boot/compressed/vmlinux.bin.lz4
-rw-r--r-- 1 root root 6.2M May 28 19:23 arch/x86/boot/compressed/vmlinux.bin.lz4
```

**Comment by FAMILIAR-project** [comment]
lzo and some tools are needed to compress the kernel... 
We should include them in the Dockerfile

**Comment by alemasle** [comment]
I just added lzop and liblz4-tools in order to compress with .lzo and .lz4 and complet the panel of possible compressions.

**Comment by alemasle** [comment]
`get_kernel_size()` est passée en "deprecated" et remplacée par `get_size_kernel()` qui calcule la taille du noyau vmlinux, de plus, une nouvelle fonction `get_compressed_size()` permet quant à elle de récupérer les 18 tailles de noyaux compressés et leur dérivés. ( bzImage pour chaque compressions, vmlinux.bin, vmlinux ... )
