### ISSUE TITLE
Package libelf-dev 

### ISSUE THREAD

**Issue by alemasle** [TuxML/ProjetIrma#82]
Lors de la commande "make" manuellement sur le dossier Linux sur un conteneur Docker, un warning apparaît pour nous demander d'installer `libelf-dev`:

```
Makefile:936: "Cannot use CONFIG_STACK_VALIDATION, please install libelf-dev, libelf-devel or elfutils-libelf-devel"
```
Serait-ce interessant de l'installer afin de peut être obtenir des compilations plus complètes?

**Comment by alemasle** [comment]
Il semble que ce package ne soit pas indispensable et sert plutôt à de la validation et au Debug.

https://github.com/torvalds/linux/blob/master/tools/objtool/Documentation/stack-validation.txt

```
It has a "check" subcommand which
analyzes every .o file and ensures the validity of its stack metadata.
It enforces a set of rules on asm code and C inline assembly code so
that stack traces can be reliable.
```
Dans notre cas je pense que l'on peut passer à coté sans poser de problèmes.

**Comment by FAMILIAR-project** [comment]
Merci, très bon "report" et belle investigation. 

Deux choses me viennent en tête:
 * ce serait intéressant d'analyser *automatiquement* les logs et la palanquée de warning qui doivent s'y trouver (a minima un petit programme qui repère les warnings s'il y en a)... je m'en charge
 * ce serait intéressant de savoir combien l'étape qui implique CONFIG_STACK_VALIDATION prend de temps... dans les "logs" on n'a pas les timestamps précis je crois, dommage (un outil de ce genre: https://github.com/paypal/gnomon serait pas déconnant... "ts" de moreutils fait le travail)

**Comment by alemasle** [comment]
Le module ts a été ajouté et est désormais présent dans les fichiers de Logs
