### ISSUE TITLE
Predefined options of tinyconfig and large campaign 

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#91]
Hi, 

"make tinyconfig" is interesting since it gives very small kernels (and also it is quite fast). 
A general objective is to use machine learning in order to discover/re-find/validate what options are causing such a kernel size reduction (execution time is also interesting, but more subtle to instrument because of heterogeneous machines we are using). 

The preliminary results show that we have small kernels, but not as small as tinyconfig. 
The first task is to verify it (with Jupyter scripts) and to have a better idea on influential options. 
We are on the right way here.  

A second task is to specialize the configurations upfront. That is, instead of a basic randconfig and only one pre-defined option (https://github.com/TuxML/ProjetIrma/blob/master/core/tuxml.config), I propose to use options here:
https://github.com/torvalds/linux/blob/master/kernel/configs/tiny.config
and launch a campaign with such settings. 

I am expecting small kernel sizes with this setting. 
So to be clear: tiny.config + tuxml.config + make randconfig (there is randomness, but pre-defined options are set) 

Final note: looking at make tiny config, it's actually allno.config + tiny.config
https://github.com/torvalds/linux/blob/master/scripts/kconfig/Makefile#L117-L118
(allno.config is created here: https://github.com/torvalds/linux/blob/master/scripts/kconfig/conf.c#L616) 
but I propose to start with tiny.config only (not allno.config)

So in a nusthell: **can we launch a large campaign ASAP with 
tiny.config + tuxml.config + make randconfig?**

**Comment by FAMILIAR-project** [comment]
An additional subtle point:
https://github.com/torvalds/linux/blob/master/arch/x86/configs/tiny.config 

it's a "complement" to the original tiny.config 
As we are necessarily targeting x86, I think it's good to include such pre-defined options

**Comment by alemasle** [comment]
It will be my next task, i take care of it.

**Comment by alemasle** [comment]
The option "--tiny" has been added on `MLfood.py`which is used to added the pre-set options of tiny.config to a randconfig file and tuxml.config.

By running ./MLfood 1 --dev --tiny, your compilation will be done with the tiny options in.

**Comment by alemasle** [comment]
This version is done without the allno configuration

**Comment by FAMILIAR-project** [comment]
Cool its what we want (only tiny). Is it still random after the predefinition of options ? x86_64 is included ?

**Comment by alemasle** [comment]
x86_64 AND the tiny pre defined options are in the random .config.
It is still random and take account of what options we asked for.

**Comment by alemasle** [comment]
It is really **tiny.config + tuxml.config + make randconfig**

**Comment by alemasle** [comment]
I close this issue, we can set predefine options in `tuxml.config` as we want and mix it up with random config.
