### ISSUE TITLE
Config to CSV

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#92]
Hello, 

L'objectif est d'obtenir un CSV "complet" avec pour chaque configuration les mesures/indicateurs associés. On a une partie de la procédure (celles sur les mesures), maintenant il faut la partie qui transforme les .config en CSV, et enfin intégrer le tout. 

De ce que j'ai compris l'algo de Pierre fonctionne ainsi:
1. d'abord il récupère toutes les options possibles et leurs types à l'aide de kconfig (https://github.com/TuxML/Kanalyser/blob/master/filltypes.sh https://github.com/TuxML/Kanalyser/blob/master/filltypes.py) et il les met dans une base de données "Properties". Je pense qu'on n'a pas besoin de relancer cette procédure, elle est indépendante des .configs 
2. ensuite il y a le genCSV.py qui est vraiment ce qui nous intéresse... 

Ce script *en l'état* produit autant de lignes CSVs qu'il y a d'entrées dans la base de données. 
**Je conseille, dans une phase de prototypage, de ne considérer que les 1000 dernières entrées de la base, histoire d'avoir un CSV facile à charger/analyser et de vérifier que c'est bien ce CSV là qu'on veut** 
Après petit à petit, on peut monter le nombre d'entrées évidemment. Mais c'est vrai que les gros CSV de ~2 Go sont "challenging" à lire (j'ai réussi avec le langage R, mais il ne m'a trouvé que ~20K entrées tout comme wc -l d'ailleurs, bizarre). 

Les headers sont toutes les options possibles, mais pas que! En fait Pierre a aussi intégré le temps de compilation et la taille: https://github.com/TuxML/csvgen/blob/master/genCSV.py#L148-L149
Donc une chose à réaliser ici: **rajouter le code Python pour collecter toutes les mesures sur les tailles** (note: autrement dit, on pourrait envisager une procédure complète qui réalise le travail en une seule fois, et éviter les concaténations/fusions dont on a parlé) 

Enfin dernier détail: dans un .config il n'y a que les options inclus ("y" ou "m"). 
Si l'option n'est pas présente, alors elle prend une valeur par défaut: 
https://github.com/TuxML/csvgen/blob/master/genCSV.py#L15-L23
typiquement "n" pour les options booléens. 

Au final je pense que le code de Pierre est réutilisable et adaptable.

**Comment by alemasle** [comment]
En réalité je n'ai qu'a modifié son script afin de l'appliquer a des .configs particulirers, par exemple le csv que je génère au fur et à mesure grâce à kernels2csv.py pourra intégrer l'utilsation du script de Pierre modifié et rajouter une colonne dans le csv. Ainsi lorsque je demanderai de nouvelles valeurs à mettre dans ce csv, on y retrouvera le csv à la manière de Pierre dans le csv du script. Je l'y met de façon compressé.

**Comment by alemasle** [comment]
Pour faire plus simple, chaque entrée du csv contiendra son .config associé sous forme de csv représentant ses options activées ou non

**Comment by alemasle** [comment]
Je ferme l'issue, les scripts de création du csv sont créés et fonctionnel. ( Voir `bdd2csv.ipynb` )

**Comment by alemasle** [comment]
Le script de Pierre a d'ailleurs été corrigé car il publiait quelques doublons dans la base "Properties"
