### ISSUE TITLE
CSV extraction

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#93]
On a large CSV, I use R to load the dataset.

library(readr)
config_bdd <- read_csv("/Users/macher1/Documents/RESEARCH/INPROGRESS/tuxml-irma/ProjetIrma/csv_kernels/config_bdd.csv")

Warning message:
Duplicated column names deduplicated: 'PGTABLE_LEVELS' => 'PGTABLE_LEVELS_1' [399], 'ARCH_MMAP_RND_BITS_MIN' => 'ARCH_MMAP_RND_BITS_MIN_1' [403], 'ARCH_MMAP_RND_BITS_MAX' => 'ARCH_MMAP_RND_BITS_MAX_1' [404], 'ARCH_MMAP_RND_COMPAT_BITS_MIN' => 'ARCH_MMAP_RND_COMPAT_BITS_MIN_1' [408], 'ARCH_MMAP_RND_COMPAT_BITS_MAX' => 'ARCH_MMAP_RND_COMPAT_BITS_MAX_1' [409], 'X86_EXTENDED_PLATFORM' => 'X86_EXTENDED_PLATFORM_1' [606], 'NO_BOOTMEM' => 'NO_BOOTMEM_1' [796], 'ARCH_ENABLE_SPLIT_PMD_PTLOCK' => 'ARCH_ENABLE_SPLIT_PMD_PTLOCK_1' [910], 'ARCH_ENABLE_HUGEPAGE_MIGRATION' => 'ARCH_ENABLE_HUGEPAGE_MIGRATION_1' [911], 'PCI_MMCONFIG' => 'PCI_MMCONFIG_1' [1143], 'HAVE_GENERIC_GUP' => 'HAVE_GENERIC_GUP_1' [1332], 'TCP_CONG_CUBIC' => 'TCP_CONG_CUBIC_1' [1425], 'VHOST_RING' => 'VHOST_RING_1' [3373], 'SUNGEM_PHY' => 'SUNGEM_PHY_1' [3393], 'SND_PXA2XX_AC97' => 'SND_PXA2XX_AC97_1' [8462], 'GOLDFISH' => 'GOLDFISH_1' [10524], 'DEFAULT_IO_DELAY_TYPE' => 'DEFAULT_IO_DELAY_TYPE_1' [12292], 'DEFAULT_IO_DELAY_TYPE' ... <truncated>

**Comment by FAMILIAR-project** [comment]
I have used a CSV extracted with the procedure: 
From = 50510
    To = 76510

**Comment by FAMILIAR-project** [comment]
The warning of Python is not that helpful: 
/usr/local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (2189,11858,12250,12340,12341,12364,12369,12378,12384) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

**Comment by alemasle** [comment]
Effectively, it seems there are duplicates, i am looking for the source of this

```
>>> with open("config_bdd.csv", "r") as file:
...     k = file.readline()
...     t = k.split(",")
...     s = set(t)
...     print("t:", len(t), "  s:", len(s))
... 
t: 12819   s: 12798

```

**Comment by alemasle** [comment]
I found all the culprit:
```
res: ['ARCH_MMAP_RND_BITS_MIN', 'ARCH_MMAP_RND_BITS_MAX', 'ARCH_MMAP_RND_COMPAT_BITS_MIN', 'ARCH_MMAP_RND_COMPAT_BITS_MAX', 'PGTABLE_LEVELS', 'GOLDFISH', 'X86_EXTENDED_PLATFORM', 'NO_BOOTMEM', 'HAVE_GENERIC_GUP', 'ARCH_ENABLE_SPLIT_PMD_PTLOCK', 'ARCH_ENABLE_HUGEPAGE_MIGRATION', 'PCI_MMCONFIG', 'TCP_CONG_CUBIC', 'BCH_CONST_M', 'BCH_CONST_T', 'VHOST_RING', 'SUNGEM_PHY', 'SND_PXA2XX_AC97', 'DEFAULT_IO_DELAY_TYPE', 'DEFAULT_IO_DELAY_TYPE', 'DEFAULT_IO_DELAY_TYPE', 'DEFAULT_IO_DELAY_TYPE', 'DEFAULT_IO_DELAY_TYPE', 'DEFAULT_IO_DELAY_TYPE']
```

**Comment by FAMILIAR-project** [comment]
Nice! 
I have issues even with 
 From = 54510 
    To = 56610

rawtuxdata[rawtuxdata['vmlinux'] == 1168072][['cid', 'CC_OPTIMIZE_FOR_SIZE']]
cid	CC_OPTIMIZE_FOR_SIZE
1903	56589	n
1904	56590	n
1905	56591	n

So we need to correct bdd2csv

**Comment by FAMILIAR-project** [comment]
DtypeWarning: Columns (114,383,1040,1150,3394,6015,6026,6717,6719,7350,7676,7726,8507,8784,10442) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

the "column duplicates" problem seem not an issue here 
t: 12798   s: 12798

**Comment by FAMILIAR-project** [comment]
From = 56580 
    To = 56593
fails 

  From = 56588
    To = 56593 
works

(for checking I am using TUXML_basic, the first "cell" for loading the CSV and then 
rawtuxdata[rawtuxdata['vmlinux'] == 1168072][['cid', 'CC_OPTIMIZE_FOR_SIZE']])

**Comment by alemasle** [comment]
A correction has been pushed on the repository, I close the issue.
