### ISSUE TITLE
Make tinyconfig

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#97]
Configurations with make tinyconfig in the database are with X86_32
ie 
CONFIG_X86_32=y
It explains why we have a few configurations with X86_32=y in the database

So we have to re-compute the real tinyconfig, this time with X86_64 (the architecture can dramatically change the results)

So we should launch make tinyconfig with CONFIG_X86_64=y 
To do so, it is the same story than with make randconfig (we can preset some options with the command line with the environment variable KCONFIG_ALLCONFIG) 

I would like to have the results:
 * with our Docker image 
 * with our Debian image 
(should be the same) 

This computation should rely on TUXML and the results should be in the database

**Comment by alemasle** [comment]
The tiny with X64 has been compiled and the result is the same for Docker or Debian from grid, about 7Mo (Docker cid = 88035 and Grid cid = 88041)
