### ISSUE TITLE
VBOXVIDEO (compilation failure: kernel Linux bug)

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#99]
When GENERIC_ALLOCATOR=n **and** DRM_VBOXVIDEO=y, it seems there is a bug

```
config DRM_VBOXVIDEO
	tristate "Virtual Box Graphics Card"
	depends on DRM && X86 && PCI
	select DRM_KMS_HELPER
	help
	  This is a KMS driver for the virtual Graphics Card used in
	  Virtual Box virtual machines.

	  Although it is possible to builtin this module, it is advised
	  to build this driver as a module, so that it can be updated
	  independently of the kernel. Select M to built this driver as a
	  module and add support for these devices via drm/kms interfaces.
```

```
Cyclomatic Complexity 3 drivers/video/fbdev/uvesafb.c:uvesafb_exit
drivers/staging/vboxvideo/vbox_hgsmi.o: In function `hgsmi_buffer_alloc':
vbox_hgsmi.c:(.text+0x24): undefined reference to `gen_pool_dma_alloc'
drivers/staging/vboxvideo/vbox_hgsmi.o: In function `hgsmi_buffer_free':
vbox_hgsmi.c:(.text+0x105): undefined reference to `gen_pool_free'
drivers/staging/vboxvideo/vbox_hgsmi.o: In function `hgsmi_buffer_submit':
vbox_hgsmi.c:(.text+0x11e): undefined reference to `gen_pool_virt_to_phys'
drivers/staging/vboxvideo/vbox_main.o: In function `vbox_hw_fini':
vbox_main.c:(.text+0x14a): undefined reference to `gen_pool_destroy'
drivers/staging/vboxvideo/vbox_main.o: In function `vbox_driver_load':
vbox_main.c:(.text+0x552): undefined reference to `gen_pool_create'
vbox_main.c:(.text+0x57f): undefined reference to `gen_pool_add_virt'
vbox_main.c:(.text+0x58f): undefined reference to `gen_pool_destroy'
make: *** [vmlinux] Error 1
```

Looking at the source code of vbox_main.c, there are indeed references to function gen_pool_*

```
static int vbox_hw_init(struct vbox_private *vbox)
{
	int ret = -ENOMEM;

	vbox->full_vram_size = inl(VBE_DISPI_IOPORT_DATA);
	vbox->any_pitch = vbox_check_supported(VBE_DISPI_ID_ANYX);

	DRM_INFO("VRAM %08x\n", vbox->full_vram_size);

	/* Map guest-heap at end of vram */
	vbox->guest_heap =
	    pci_iomap_range(vbox->dev->pdev, 0, GUEST_HEAP_OFFSET(vbox),
			    GUEST_HEAP_SIZE);
	if (!vbox->guest_heap)
		return -ENOMEM;

	/* Create guest-heap mem-pool use 2^4 = 16 byte chunks */
	vbox->guest_pool = gen_pool_create(4, -1);
	if (!vbox->guest_pool)
		goto err_unmap_guest_heap;

	ret = gen_pool_add_virt(vbox->guest_pool,
				(unsigned long)vbox->guest_heap,
				GUEST_HEAP_OFFSET(vbox),
				GUEST_HEAP_USABLE_SIZE, -1);
	if (ret)
```

It seems to be a very recent code:
https://lwn.net/Articles/729653/ 
https://www.mail-archive.com/netdev@vger.kernel.org/msg194998.html 

A further investigation shows that 

`#include "vbox_drv.h"` is part of vbox_main.c
and this .h file contains

```
#ifndef __VBOX_DRV_H__
#define __VBOX_DRV_H__

#include <linux/genalloc.h>
```

So normally gen_pool_* functions should exist

**Comment by FAMILIAR-project** [comment]
Note:
`GENERIC_ALLOCATOR == 'n' & DRM_VBOXVIDEO == 'm'`
ie DRM_VBOXVIDEO as a module does not lead to a compilation error

`DRM_VBOXVIDEO == 'y'`
ie without GENERIC_ALLOCATOR as no value does not lead to a compilation error

**Comment by FAMILIAR-project** [comment]
And here is the full explanation (and the Kconfig patch):
https://lkml.org/lkml/2017/7/28/349 

strangely, it has not been integrated (patch was end of july; release of 4.13.3 was beginning of september: https://lkml.org/lkml/2017/9/20/184)

**Comment by alemasle** [comment]
So we force these two options to "n"?

**Comment by FAMILIAR-project** [comment]
No this case is more subtle and the pre-setting is less straightforward (it is about two specific values of two options, not about values of individual option) 

Nevermind, we let such a failure occurs at the moment. However the conclusion here is that we do have found a configuration bug with TUXML

**Comment by FAMILIAR-project** [comment]
https://github.com/torvalds/linux/blob/v4.13/drivers/staging/vboxvideo/Kconfig
https://github.com/torvalds/linux/commit/33ad3fdcf95a552486cf8a95543037d8ebb069f6#diff-1d667aeaa4690c608b3ba99a940b761b
https://github.com/torvalds/linux/blob/v4.14/drivers/staging/vboxvideo/Kconfig#L6

**Comment by FAMILIAR-project** [comment]
see also https://github.com/TuxML/ProjetIrma/issues/164
